---
title: "¿Porqué se necesitan las almas víctimas? , Salvador Thomassiny"
thumb: "https://i.ytimg.com/vi_webp/IyGzo0LUREo/maxresdefault.webp"
tags: [Mundo Católico]
---

 # ¿Porqué se necesitan las almas víctimas? - Salvador Thomassiny 

 <iframe width="560" height="315" src="https://www.youtube.com/embed/IyGzo0LUREo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> 

 ## Content 


[00:00:01](https://www.youtube.com/watch?v=IyGzo0LUREo&t=0.67s&t=1s) -> 00:00:16 : [Música] el reino de la divina voluntad ya está en medio de las criaturas escucha la espiritualidad dictada a Luisa picarreta por el  
[00:00:13](https://www.youtube.com/watch?v=IyGzo0LUREo&t=12.679s&t=13s) -> 00:00:33 : especialista el doctor Salvador tomasini aquí por mundo católico construyendo la civilización del [Música] amor amigos Cómo están aquí nos  
[00:00:31](https://www.youtube.com/watch?v=IyGzo0LUREo&t=31.48s&t=31s) -> 00:00:45 : encontramos nuevamente en nuestro programa de la divina voluntad y Contamos con la asistencia de Cecilia s gracias doctor por invitar a su programa el día de hoy con un tema muy  
[00:00:43](https://www.youtube.com/watch?v=IyGzo0LUREo&t=42.719s&t=43s) -> 00:00:59 : interesante Así es como todos No sí como todos pero cuéntenos pero nos nos decías que quería que tú querías que habláramos sobre el alma víctima no yo creo que se necesita mucho doctor porque  
[00:00:55](https://www.youtube.com/watch?v=IyGzo0LUREo&t=55.16s&t=55s) -> 00:01:12 : eh Cuál es la la razón o la necesidad de que haya almas víctimas creo que esto es muy importante y también por qué no tenerle miedo o sea en positivo por qué no tenerle miedo a este llamado porque a  
[00:01:10](https://www.youtube.com/watch?v=IyGzo0LUREo&t=69.52s&t=70s) -> 00:01:22 : veces pensamos que ser alma víctima es un llamado para algunos para algunos Escogidos o y algunos que tengan por la capacidad de hacerlo porque no no es así no no no todo el mundo no sí como que es  
[00:01:21](https://www.youtube.com/watch?v=IyGzo0LUREo&t=81.24s&t=81s) -> 00:01:34 : un llamado para algunos sin no para todos Qué bueno dice uno así es almas víctimas Sí pero en ti no en mí sí qué bueno Tú eres un alma víctima lo Cele pero yo porque no me toca a mí en mi  
[00:01:31](https://www.youtube.com/watch?v=IyGzo0LUREo&t=91.28s&t=91s) -> 00:01:50 : casa Así es bueno primero hay que definir Qué es un alma víctima un alma víctima es aquella alma a la cual Jesús primero le pregunta si quiere todas las cosas de Dios siempre son voluntarias  
[00:01:46](https://www.youtube.com/watch?v=IyGzo0LUREo&t=105.92s&t=106s) -> 00:02:09 : Nunca es algo impuesto cuando el alma acepta acepta tener este oficio de Alma víctima lo que está eh aceptando es participar en la pasión de Jesús o sea convertirse en una actualización  
[00:02:05](https://www.youtube.com/watch?v=IyGzo0LUREo&t=124.96s&t=125s) -> 00:02:28 : de la pasión de Jesús por qué esto para qué para qué es esto Jesús nos dice que el alma bueno las personas tenemos que cooperar con él y mantener este estado de sufrimiento de su  
[00:02:24](https://www.youtube.com/watch?v=IyGzo0LUREo&t=143.599s&t=144s) -> 00:02:41 : humanidad Pero para estar continuamente reparando por los pecados de todo el mundo Sí o sea él en su humanidad lo hizo todo pero su humanidad ya es gloriosa ya no puede seguir sufriendo  
[00:02:38](https://www.youtube.com/watch?v=IyGzo0LUREo&t=157.92s&t=158s) -> 00:02:59 : Pero él necesita de alguna manera que el sufrimiento continúe para eh servir como un para rayos a la justicia divina también nos dice los escritos de Luisa picarreta que si un hubiera  
[00:02:56](https://www.youtube.com/watch?v=IyGzo0LUREo&t=175.84s&t=176s) -> 00:03:13 : faltado alguna vez por 15 minutos un alma víctima hubiera destruido todo porque no habría habido un sostén para para para la humanidad y algo que frenara la justicia  
[00:03:11](https://www.youtube.com/watch?v=IyGzo0LUREo&t=190.72s&t=191s) -> 00:03:31 : divina Por qué la justicia divina porque la justicia se tiene que Descargar o sea es aquello que hablábamos del equilibrio de Dios Entonces la justicia divina está motivada por las culpas de nosotros para  
[00:03:28](https://www.youtube.com/watch?v=IyGzo0LUREo&t=207.599s&t=208s) -> 00:03:47 : descargarse pero si hay una alma que reciba sobre ella todo lo el la Cómo diríamos la fuerza de la justicia divina ella tomaría sobre de ella misma el castigo que merecemos todos interesante  
[00:03:44](https://www.youtube.com/watch?v=IyGzo0LUREo&t=224.4s&t=224s) -> 00:04:06 : y uniéndolos al sacrificio de Jesús entonces tiene un valor infinito y tiene un valor prácticamente diríamos como Redentor por lo tanto tenemos este punto alma víctima que se presta a sufrir los  
[00:04:03](https://www.youtube.com/watch?v=IyGzo0LUREo&t=242.76s&t=243s) -> 00:04:18 : todas las sufrimientos de la pasión de Jesús y físicamente a mí me gustaría como ampliarle un poco el concepto y preguntarle en esta ampliación cuando usted dice la pasión de Jesús es que  
[00:04:17](https://www.youtube.com/watch?v=IyGzo0LUREo&t=256.88s&t=257s) -> 00:04:30 : para mí la pasión de Jesús no es solamente desde el jueves Santo verdad O sea que vamos a decir desde el huerto Dean hasta su muerte sino para m la pasión de Jesús es desde el momento en  
[00:04:27](https://www.youtube.com/watch?v=IyGzo0LUREo&t=266.96s&t=267s) -> 00:04:46 : que él nace desde que se Encarna s pero estamos Perdón estamos hablando ahorita del alma víctima tradicional Ah okay Okay lo que ha habido desde el momento de que Jesús estuvo en la tierra  
[00:04:42](https://www.youtube.com/watch?v=IyGzo0LUREo&t=282.24s&t=282s) -> 00:05:04 : hasta el momento actual que son almas víctima que se prestan nada más a a sufrir en ellas la los todos los sufrimientos de Jesús la corona de espinas la los los flagelos incluso la  
[00:05:00](https://www.youtube.com/watch?v=IyGzo0LUREo&t=300.12s&t=300s) -> 00:05:20 : cruz los clavos o sea todos los estigmatizados que es la parte física del sufrimiento de Jesús y que eso es lo que conocíamos prácticamente tenemos  
[00:05:16](https://www.youtube.com/watch?v=IyGzo0LUREo&t=315.88s&t=316s) -> 00:05:36 : una historia de la pasión de Jesús de 20 horas O sea eso es lo que hemos tenido tenido hasta ahora como como punto de la pasión de Jesús hasta ahora hasta ahora ahora viene esta  
[00:05:33](https://www.youtube.com/watch?v=IyGzo0LUREo&t=333.12s&t=333s) -> 00:05:51 : nueva revelación esta esta revelación privada Luisa picarreta donde Jesús nos habla de que su pasión no es nada más aquella sino que su pasión fue triple tres pasiones la pasión del amor  
[00:05:49](https://www.youtube.com/watch?v=IyGzo0LUREo&t=348.96s&t=349s) -> 00:06:09 : La pasión del pecado y la pasión del del hombre del judío del del Romano pero el para entender estas pasiones necesitamos entender primero qué es lo que vino a hacer Jesús a este  
[00:06:04](https://www.youtube.com/watch?v=IyGzo0LUREo&t=364.28s&t=364s) -> 00:06:25 : mundo O sea la idea original de Dios de la Encarnación del verbo era para que el verbo pudiera venir a reinar en este mundo el reino de Dios en la tierra el cual iba a estar Jesús en a la cabeza y  
[00:06:23](https://www.youtube.com/watch?v=IyGzo0LUREo&t=382.68s&t=383s) -> 00:06:41 : Jesús reinando en el corazón de cada uno de nosotros en el alma de cada uno de nosotros eso se pierde en el paraíso terrenal y ahora en la la ese ese esa finalidad ya  
[00:06:38](https://www.youtube.com/watch?v=IyGzo0LUREo&t=397.639s&t=398s) -> 00:06:56 : no se puede llevar a cabo entonces Dios tiene un plan emergente y ese plan emergente es La redención que generalmente la hemos confundido con la salvación y le hemos aplicado todo el  
[00:06:54](https://www.youtube.com/watch?v=IyGzo0LUREo&t=413.56s&t=414s) -> 00:07:09 : valor de la pasión de Jesús se lo hemos aplicado a la salvación del hombre Qué es la ación del hombre que algún día cuando te mueras aunque pases por el purgatorio pero que puedas llegar a la  
[00:07:06](https://www.youtube.com/watch?v=IyGzo0LUREo&t=425.84s&t=426s) -> 00:07:23 : presencia de Dios a vivir con él cosa que no podían hacer todos los del Antiguo Testamento o sea el Antiguo Testamento estaban muertos a la gracia y por lo tanto no podían entrar al cielo  
[00:07:20](https://www.youtube.com/watch?v=IyGzo0LUREo&t=439.96s&t=440s) -> 00:07:41 : Entonces Jesús viene y nos hemos quedado en esa restitución de la gracia y que ya podemos Acceder al cielo a la presencia de Dios pero nada más ahí lo dejamos por lo tanto el valor el mérito la persona  
[00:07:37](https://www.youtube.com/watch?v=IyGzo0LUREo&t=457.199s&t=457s) -> 00:08:00 : de de Jesús que es persona divina le da el suficiente Cómo diríamos valor precio para que Dios conceda el perdón pero no era esa la finalidad única de la de La redención la finalidad  
[00:07:55](https://www.youtube.com/watch?v=IyGzo0LUREo&t=475.44s&t=475s) -> 00:08:14 : primaria primaria es restituirle a la al padre todo lo que el hombre no le había dado primera cosa Qué es lo que no le había dado el amor que Dios requería toda la el agradecimiento por  
[00:08:12](https://www.youtube.com/watch?v=IyGzo0LUREo&t=491.96s&t=492s) -> 00:08:30 : todo lo que tenía el reconocimiento de todo lo que nos ha dado y sobre todo tomar todo lo que el padre había sacado de él para nosotros para vivirlo nosotros y que nosotros lo dejamos a un  
[00:08:26](https://www.youtube.com/watch?v=IyGzo0LUREo&t=505.96s&t=506s) -> 00:08:46 : lado ahora el hombre tiene que volver tomar eso pero no puede entonces tiene que venir Jesús a rehacer al hombre para darle lo que antes tenía en el momento de la creación y en ese momento  
[00:08:43](https://www.youtube.com/watch?v=IyGzo0LUREo&t=522.88s&t=523s) -> 00:09:02 : poder tener la capacidad suficiente para recibir lo que Dios había destinado para nosotros que era una vida divina y esa vida divina vivirla nosotros como no lo hemos hecho la tiene que vivir Jesús  
[00:08:58](https://www.youtube.com/watch?v=IyGzo0LUREo&t=538.399s&t=538s) -> 00:09:17 : pero también tiene que vivir el castigo que nosotros merecemos por todo lo que hemos hecho entonces la pasión de Jesús se vuelve triple él dice pasión del amor qué es eso el amor que nosotros no le  
[00:09:16](https://www.youtube.com/watch?v=IyGzo0LUREo&t=555.6s&t=556s) -> 00:09:32 : dimos a la divinidad y que insertamos en vez de amor insertamos cosas humanas ahí hay una muerte que le estamos dando en nosotros a la divina  
[00:09:30](https://www.youtube.com/watch?v=IyGzo0LUREo&t=570.12s&t=570s) -> 00:09:48 : que debería de estar funcionando viviendo en nosotros le dimos muerte para darle vida la vida humana por lo tanto Jesús tiene que venir a revertir aquello qué necesita  
[00:09:44](https://www.youtube.com/watch?v=IyGzo0LUREo&t=584.16s&t=584s) -> 00:10:04 : hacer darle muerte a la vida humana para darle vida nuevamente a la vida divina o sea tomar todo lo que el padre había destinado para cada uno de nosotros y vivirlo él pero para  
[00:10:00](https://www.youtube.com/watch?v=IyGzo0LUREo&t=600.399s&t=600s) -> 00:10:18 : necesita matar que muera la voluntad humana Y eso sería para mí la más importante señal de ser víctima Más allá de que estemos en una cama como Luisa o que tengamos enfermedad tras enfermedad  
[00:10:16](https://www.youtube.com/watch?v=IyGzo0LUREo&t=615.56s&t=616s) -> 00:10:31 : sufi sufrimiento Sí ahorita estamos en el punto de ver qué es lo que Jesús vino a hacer a este mundo Entonces viene a sufrir una muerte por cada vez que nosotros hemos hecho un acto separado  
[00:10:30](https://www.youtube.com/watch?v=IyGzo0LUREo&t=629.839s&t=630s) -> 00:10:47 : La divina voluntad innumerables muertes infinitas infinitas muertes y Jesús dice que él tuvo que morir todas esas veces para poder  
[00:10:43](https://www.youtube.com/watch?v=IyGzo0LUREo&t=642.56s&t=643s) -> 00:11:04 : rehacer la Justicia del padre porque el padre como decíamos es un equilibrio me deben tantas vidas divinas que no les han dado vida en ellos tú me tienes que pagar tantas muertes de vida humana para  
[00:11:01](https://www.youtube.com/watch?v=IyGzo0LUREo&t=660.519s&t=661s) -> 00:11:19 : rehacer la vida divina Y eso lo el único que lo podía hacer era Dios mismo o sea el hombre es incapaz de poderle haber aplicado a Jesús todo las muertes el número de muertes que debería de haber  
[00:11:16](https://www.youtube.com/watch?v=IyGzo0LUREo&t=676.32s&t=676s) -> 00:11:32 : sufrido y entonces es el Amor divino el que tiene que írsela aplicando nada más perdone la interrupción para que no seen sus fans perdone usted le quiero quiero preguntar te burlas no no me burro pero  
[00:11:30](https://www.youtube.com/watch?v=IyGzo0LUREo&t=690.279s&t=690s) -> 00:11:44 : es que dicen que lo interrumpo y lo interrumpo pero me gustaría aclarar que no es una entrevista es un diálogo es un diálogo eh el que tengo con el doctor y se vale por Porque necesitamos entender  
[00:11:42](https://www.youtube.com/watch?v=IyGzo0LUREo&t=702.079s&t=702s) -> 00:11:56 : todos los que nos están viendo a lo mejor ve Este programa por primera vez y no van a entender prácticamente nada no entonces pues me pongo en su lugar y me gustaría que me aclarara A qué se  
[00:11:53](https://www.youtube.com/watch?v=IyGzo0LUREo&t=712.56s&t=713s) -> 00:12:10 : refiere con tantas muertes es decir cada acto que yo realizo fuera de la voluntad de Dios as haciendo mi voluntad es como es aplicarle una muerte a Dios cada acto que hemos hecho fuera o sea el contrario  
[00:12:07](https://www.youtube.com/watch?v=IyGzo0LUREo&t=727.24s&t=727s) -> 00:12:27 : a la voluntad de Dios sí es una muerte que nosotros le dimos a la vida Que dios quería vivir en nosotros en ese acto Y entonces le dimos vida a la vida humana Qué difícil sí O sea que se entienda  
[00:12:24](https://www.youtube.com/watch?v=IyGzo0LUREo&t=744.279s&t=744s) -> 00:12:40 : fuimos creados para que en cada que Dios viviera en nosotros habíamos hablado en algunos programas de que somos la maquinaria Perdón por la por la expresión Pero  
[00:12:36](https://www.youtube.com/watch?v=IyGzo0LUREo&t=756.24s&t=756s) -> 00:12:54 : somos la maquinaria perfecta para que Dios pudiera desarrollar en nosotros en el tiempo y en el espacio todas sus acciones por eso es que tenemos ojos por eso es que tenemos oídos por eso es que  
[00:12:51](https://www.youtube.com/watch?v=IyGzo0LUREo&t=771.48s&t=771s) -> 00:13:07 : tenemos olfato por eso es que tenemos piernas o sea para que Dios pudiera desarrollar sus acciones de movimiento de de hablar de todo pero a través de  
[00:13:03](https://www.youtube.com/watch?v=IyGzo0LUREo&t=783.0s&t=783s) -> 00:13:24 : nosotros Entonces cada acto nuestro debería de haber servido para que Dios pusiera un acto de él en ese acto y como Dios en cada acto que hace como Dios se mueve todo en cada momento entonces cada  
[00:13:21](https://www.youtube.com/watch?v=IyGzo0LUREo&t=800.72s&t=801s) -> 00:13:40 : acto significaría o representaría una vida de él en ese acto Sí bueno la sentencia del paraíso terrenal fue el día que comas del fruto de ese árbol irremediablemente  
[00:13:37](https://www.youtube.com/watch?v=IyGzo0LUREo&t=816.76s&t=817s) -> 00:13:55 : morirás el fruto del árbol ya sabemos era un acto de la voluntad humana separada de la voluntad divina un acto de voluntad humana solo en ese momento la la voluntad humana está adquiriendo  
[00:13:52](https://www.youtube.com/watch?v=IyGzo0LUREo&t=831.839s&t=832s) -> 00:14:09 : en Sí una muerte irremediablemente morirás una muerte tanto como física el hombre iba iba a ser inmortal no iba a morir y el hombre iba  
[00:14:06](https://www.youtube.com/watch?v=IyGzo0LUREo&t=846.199s&t=846s) -> 00:14:23 : a estar siempre en la presencia de Dios por lo tanto muerte espiritual no no existía Cuando el hombre se quita aquello se quita la vida y la voluntad divinas en ese momento lo que hace es se  
[00:14:20](https://www.youtube.com/watch?v=IyGzo0LUREo&t=859.959s&t=860s) -> 00:14:40 : queda nada más con su voluntad humana y adquiere las características de su naturaleza física tiene que morir y la la tiene que morir espiritualmente ya no tiene la gracia no tiene el acceso  
[00:14:36](https://www.youtube.com/watch?v=IyGzo0LUREo&t=875.959s&t=876s) -> 00:14:54 : directo al al al cielo ni directo ni indirecto No tiene acceso no tiene acceso por eso es que todos los del Antiguo Testamento se fueron al seno de Abraham a esperar La redención Por qué  
[00:14:51](https://www.youtube.com/watch?v=IyGzo0LUREo&t=891.32s&t=891s) -> 00:15:09 : Porque como estaba prevista La redención hubiera sido injusto que los buenos del Antiguo Testamento no tuvieran acceso a eso cl y aparte los actos divinos son universales no son particulares sino  
[00:15:07](https://www.youtube.com/watch?v=IyGzo0LUREo&t=907.079s&t=907s) -> 00:15:25 : universales por lo tanto aquellos muertos a la gracia buenos Santos algunos de ellos pero tuvieron que esperar esa restitución Qué duro ahora viene Jesús  
[00:15:22](https://www.youtube.com/watch?v=IyGzo0LUREo&t=922.04s&t=922s) -> 00:15:42 : con su con su pasión la pasión del Amor ya dijimos restituye el amor restituye esa vida esa vida divina que debería de haber vivido cada uno que lo platicamos en algún programa que eso es la parábola  
[00:15:38](https://www.youtube.com/watch?v=IyGzo0LUREo&t=937.88s&t=938s) -> 00:15:58 : del del banquete de bodas es el traje que Jesús hizo para cada uno de nosotros que es nuestra vida rehecha Y luego ya con eso Ahora tiene que tener otra pasión que es la pasión  
[00:15:54](https://www.youtube.com/watch?v=IyGzo0LUREo&t=954.04s&t=954s) -> 00:16:15 : del pecado la pasión del pecado es cada acto se de la voluntad de Dios merece una pena Sí y se se prefigura o se figura como por cada pensamiento malo una  
[00:16:11](https://www.youtube.com/watch?v=IyGzo0LUREo&t=971.0s&t=971s) -> 00:16:29 : espina por cada acción mala un un flagelo por en fin es una forma así metafórica de aplicar nuestra desobediencia nuestra falta contra Dios y lo que necesitaríamos sufrir para que  
[00:16:25](https://www.youtube.com/watch?v=IyGzo0LUREo&t=985.36s&t=985s) -> 00:16:45 : quedara saldada esa deuda como no lo podríamos sufrir nosotros Entonces él lo toma como alma víctima porque es un alma víctima es la víctima por excelencia y él tiene que sufrir todo aquello pero no  
[00:16:43](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1002.519s&t=1003s) -> 00:17:04 : puede ser en un momento dado también es desde el momento mismo de su Encarnación que empieza a a padecerlo entonces la pasión de Jesús se desarrolla durante toda su vida no es las últimas 20 horas  
[00:17:00](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1020.0s&t=1020s) -> 00:17:22 : es toda su vida desde el momento de la Encarnación y es la divinidad del Amor divino quien le está aplicando la quien le está eh dando todo aquello que necesita para rehacer al hombre por lo  
[00:17:18](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1038.0s&t=1038s) -> 00:17:38 : tanto la parte de la de la salvación es la parte mínima mínima y al mismo tiempo es la parte secundaria o terciaria Pero tiene que ser la primera en conseguirse para que  
[00:17:36](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1055.72s&t=1056s) -> 00:17:52 : todo lo demás funcione Sí por eso es que se nos aparece en en tanto en la vida de Jesús aparece en primer lugar la salvación Bueno ya está esto Esto se  
[00:17:49](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1069.44s&t=1069s) -> 00:18:09 : logró a través del sufrimiento de Jesús en todas su vida en toda su vida y en esas esferas ahora pero me faltó una la pasión del pecado y la pasión del hombre que es lo que Dios no le podía  
[00:18:03](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1083.2s&t=1083s) -> 00:18:22 : dar que era el odio la La venganza La este los pecados capitales todos los pecados capitales por eso los pecados capitales pero yo me refiero Dios no podía ser Injusto con con él Dios no  
[00:18:18](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1098.44s&t=1098s) -> 00:18:42 : podía ser descargar esa animalidad que el hombre tiene para hacer todo aquello el hombre no Dios no podía apar le todo ese sufrimiento de golpes de escupi dinas de odio así tremendo hacia hacia  
[00:18:39](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1119.36s&t=1119s) -> 00:18:56 : aquella persona eso no se lo puede dar Dios no lo tiene entonces eso se lo deja al hombre la parte la parte final y Jesús dice que si el trabajo de que él tenía  
[00:18:54](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1133.84s&t=1134s) -> 00:19:14 : que hacer aquí hubiera sido nada más la salvación hubiera bastado una su sangre o sus lágrimas para que el padre hubiera perdonado pero no se trataba nada más de perdón sino de restitución ese es el  
[00:19:10](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1150.48s&t=1150s) -> 00:19:28 : punto y eso es lo que lleva el victimado de Jesús a este grado Bueno ahora Jesús nosotros participamos estas tres junto con Jesús por eso nosotros usufruct esas  
[00:19:25](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1165.039s&t=1165s) -> 00:19:44 : tres o sea tenemos posibilidad de tomarlas y aplicarlas a nosotros pero falta lo que le faltó a la pasión de Jesús y eso dicho por San Pablo necesitamos  
[00:19:41](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1180.799s&t=1181s) -> 00:20:01 : completar en nosotros lo que le faltó a la pasión de Jesús y el catecismo de la Iglesia Católica como que le aumenta todavía sí o sea porque dijo San Pablo no no no lo dijo  
[00:19:57](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1196.52s&t=1197s) -> 00:20:16 : todo está dificils no porque dice que necesitamos cumplir en nosotros los misterios y los estados de Jesús catecismo de la Iglesia Católica por lo tanto no es nada más la pasión  
[00:20:13](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1212.679s&t=1213s) -> 00:20:31 : sino son los misterios y los Estados Qué es eso toda su vida los estados donde él Aparentemente estaba bien don su predicación su vida oculta todo lo que él hizo eso lo necesitamos repetir en  
[00:20:28](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1227.559s&t=1228s) -> 00:20:48 : nosotros okay y él hace según el catecismo no solo que lo que lo repita en nosotros sino que nosotros lo podamos vivir En él o sea como que nos nos quita la distancia del tiempo y nos dice  
[00:20:45](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1244.679s&t=1245s) -> 00:21:02 : ustedes van a estar en Jesús hace 2000 años sufriendo esto vamos a integrar viviendo esto pero ahora él viene aquí y aquí lo tiene que pasar en ustedes ustedes tienen que aceptar esto y unirse  
[00:21:00](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1259.96s&t=1260s) -> 00:21:19 : a la pasión de Jesús por eso Jesús tiene su pasión también en nosotros Claro así es de manera Mística no Ajá y necesita él quiere que la criatura participe en esto porque su humanidad ya está en el  
[00:21:15](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1275.24s&t=1275s) -> 00:21:37 : cielo Ya es incapaz de de sufrir pero requiere de almas que estén de alguna manera prestándole su humanidad a él para continuar en el tiempo en el tiempo su pasión y esas son las almas víctimas  
[00:21:34](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1293.84s&t=1294s) -> 00:21:53 : que hemos conocido pero se limitaba nada más a lo que a lo que él Había decidido comunicarle a la criatura y lo único que decidió comunicarle es la pasión del último día de su vida pero no no todo lo  
[00:21:51](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1310.799s&t=1311s) -> 00:22:06 : anterior No todo lo anterior lo anterior eso quedó oculto interesante entonces queda la la pasión de Jesús como la últimas 20 horas y ahí es donde las almas víctimas que ha habido hasta  
[00:22:03](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1322.84s&t=1323s) -> 00:22:19 : ahorita es lo que han lo que han lo que han tenido lo que han tenido poro han tenido la coración de espinas han tenido los los estigmas han tenido esa parte así es y hemos conocido unos cuantos La  
[00:22:16](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1335.52s&t=1336s) -> 00:22:31 : verdad sí unos cuantos Pero hay miles de almas víctima que ni idea tenemos anónimos que sufren la pasión de Jesús a mí en lo personal me me ha tocado conocer dos  
[00:22:29](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1349.279s&t=1349s) -> 00:22:44 : que nadie conoce que nadie nada pero de repente sufren la pasión de Jesús tienen tienen el la coronación de espinas el sangrado el sangrado del corazón Yo también conozco unos anónimos y que son  
[00:22:41](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1361.32s&t=1361s) -> 00:22:55 : anónimos y además es algo impactante Así es es impactante porque una persona que está Aparentemente bien y de repente le empiezan a aparecer Golpes en el cuerpo sin ninguna razón y le empieza a sangrar  
[00:22:52](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1372.48s&t=1372s) -> 00:23:05 : y le empieza empieza a no poder ni caminar ni hablar ni nada se le tiene que postrar en una cama eh son personas de Dios estamos hablando de personas de Dios no de personas este que están  
[00:23:03](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1382.679s&t=1383s) -> 00:23:16 : sumergidas en en alguna extraña filosofía sino personas que viven los sacramentos que los practican que tienen una vida noble y que sufren esto que no tienen en el que no tienen ningún signo  
[00:23:14](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1393.559s&t=1394s) -> 00:23:30 : porque esto es algo que se ha se ha tomado a veces como cuestión del enemigo Claro claro o sea yo no yo no digo que que no lo pudiera ser pero estas son como tú dices almas de Dios almas que se  
[00:23:26](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1406.32s&t=1406s) -> 00:23:45 : han entregado a Dios a ayudarlo vamos a ponerlo así en continuar su pasión y y Esas son las que conocemos ahorita Así es bueno eso es hasta antes de Luisa que es el Vivir la pasión de Jesús pero en  
[00:23:42](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1422.32s&t=1422s) -> 00:24:00 : la parte conocida en la parte eh corporal Bueno ahora la víctima por excelencia es Jesús Claro que es la víctima que e lo que hemos dicho desde el momento de su Encarnación hasta el  
[00:23:56](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1436.48s&t=1436s) -> 00:24:13 : momento de su muerte dónde sufre estas tres pasiones Sí sí Bueno cuando el alma cuando cualquier persona que desea entrar a vivir en la divina  
[00:24:09](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1449.4s&t=1449s) -> 00:24:29 : voluntad qué es lo primero que tiene que hacer tiene que hacer exactamente lo que hizo Jesús para redimirnos tiene que llegar destruir lo humano darle muerte a la voluntad humana  
[00:24:27](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1466.6s&t=1467s) -> 00:24:44 : no a la voluntad sino al acto humano vamos a ser más precisos al acto humano para unir la voluntad humana con su voluntad y rehacer todos los actos pero en modo divino Tenemos que tener  
[00:24:42](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1481.559s&t=1482s) -> 00:24:57 : conciencia de eso claro de cada acto que hacemos por supuesto hasta de dormir y Perdona que sea tan dramática pero yo te diría tú tienes conciencia de que eres abogada Cuando duermes no tienes  
[00:24:55](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1495.2s&t=1495s) -> 00:25:08 : conciencia de que eres abogada cuando comes no gracias a Dios cuándo tienes conciencia cuando realizo un acto de abogada pero todos los demás no Qué  
[00:25:05](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1505.48s&t=1505s) -> 00:25:20 : raro no no lo veo así como que me desprendo es que es verdad no no te desprendes eres soy abogada pero no realizo mi capacidad de abogada completa cuando estoy comiendo o cuando estoy  
[00:25:17](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1517.44s&t=1517s) -> 00:25:35 : durmiendo bueno quizá con ella con con con tu profesión no pero es mi profesión sí como médico como médico yo Por ejemplo ahorita no tengo el ejercicio de la medicina en ese momento pero si yo  
[00:25:32](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1532.32s&t=1532s) -> 00:25:54 : veo a alguien y lo veo lo veo con una cara determinada una F es lo veo caminar un poquito mal digo Ah tiene esto tiene esto tiene si yo toco toco como médico o sea inmediatamente tú tocas algo alguien  
[00:25:49](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1549.48s&t=1549s) -> 00:26:06 : perdón y estás explorando cuando como veo un papel y ya lo veo como porque estás acostumbrado a eso Entonces se vuelve naturaleza en tu vida claro cuando el alma llega a vivir en la  
[00:26:04](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1563.799s&t=1564s) -> 00:26:21 : divina voluntad La divina voluntad se convierte en naturaleza de tu vida y ya no ya no tienes que estar consciente de cada acto no nos alcanzaría el tiempo si no no te alcanza Entonces se vuelve  
[00:26:17](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1577.32s&t=1577s) -> 00:26:38 : naturaleza y en ese momento es que empieza a funcionar ese victimado Porque empezamos a darle muerte a lo nuestro a lo humano y es una muerte atroz porque es una muerte no como la muerte que  
[00:26:35](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1594.72s&t=1595s) -> 00:26:54 : Jesús sufre en la cruz sino es una muerte por cada acto es una cruz en que cada acto negándome a a lo mío y poniéndolo de Dios es un clavo que se pone Entonces es  
[00:26:50](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1610.399s&t=1610s) -> 00:27:08 : un clavo que es una crucificción que no me permite El más mínimo movimiento entonces estoy entendiendo Por qué el sacrificio es tan importante porque el sacrificio es la negativa tu voluntad  
[00:27:05](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1625.039s&t=1625s) -> 00:27:23 : claro o sea quieres comer no comes no quieres oír cosas bonitas no las Oyes quieres estrangular a alguien no lo estrangulas quieres gritar no gritas Entonces el sacrificio por eso es tan  
[00:27:20](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1639.84s&t=1640s) -> 00:27:36 : importante todas las virtudes todas las virtudes y todo lo que Jesús nos ha pedido desde antes de de que estuviera aquí o sea desde la ley mosaica es un destrúyete a ti  
[00:27:34](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1653.96s&t=1654s) -> 00:27:48 : mismo a ti mismo por supuesto es indispensable no es que sea un camino para salvación como dice Juano es el único camino es el único camino o sea deberíamos de entender esto cuando lo  
[00:27:46](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1665.64s&t=1666s) -> 00:28:01 : decimos la gente no lo capta así a la primera lo que traemos cargando no es vida es muerte porque son actos puros muerte espiritual pero como ya nadie piensa en  
[00:27:58](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1678.24s&t=1678s) -> 00:28:14 : lo espiritual Entonces cuando oyen esto dicen ay Quién sabe de qué están hablando Ya empezaron con con sus cosas ya sabes a lo que me refier pero es una muerte espiritual queramos o no queramos  
[00:28:11](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1691.36s&t=1691s) -> 00:28:29 : nos vamos a enfrentar a este mundo espiritual nos vamos a enfrentar a este Dios en un momento dado y cuando ya Quizá no haya remedio es que está fuertísimo doctor es que perdóneme está  
[00:28:26](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1706.159s&t=1706s) -> 00:28:40 : dificilísimo y por eso nos da miedo o sea por qué se necesitan las almas víctimas estoy infiriendo que es la única forma en la que yo le le doy gloria a Dios como él se lo merece Sí  
[00:28:37](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1717.32s&t=1717s) -> 00:28:58 : pero las almas víctimas anteriores eran para eh tratar de mitigar la justicia y ahora ahora es que cada cada persona tome sobre de Sí su propia cruz y haga lo que Jesús no hizo en  
[00:28:55](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1734.84s&t=1735s) -> 00:29:16 : él y que le ayude a Jesús porque la divina voluntad es es no no se limita a una criatura sino se extiende a todos es infinita y con el sufrimiento que estoy teniendo yo que es lo mismo que Jesús  
[00:29:12](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1752.48s&t=1752s) -> 00:29:33 : hizo por mí pero ahora tomado por mí es lo que Jesús hizo y eso se extiende a los demás es como si fuéramos Jesús es vivientes Así es Y ahora el alma No solo es un victimado propio en que el alma  
[00:29:29](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1768.64s&t=1769s) -> 00:29:51 : está rehaciendo sus actos por sí misma con este sacrificio que dijimos sino que Jesús en ella está rehaciendo todo lo que él hizo y eso tiene valor universal Entonces ahora el alma el alma  
[00:29:48](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1788.24s&t=1788s) -> 00:30:09 : que vive en la divina voluntad se convierte en un alma víctima completa total y esa alma víctima se extiende a ese victimado Perdón se extiende a toda la humanidad para dar lo mismo que Jesús  
[00:30:04](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1804.24s&t=1804s) -> 00:30:26 : hizo y que el alma que los demás tengan la posibilidad de tomar lo doble o lo triple o que sientan más fuerza para convertirse el el movimiento de conversión se decir No no es un  
[00:30:23](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1823.32s&t=1823s) -> 00:30:40 : movimiento que entre por los oídos no no entra por los oídos no es un moviento que entre por los ojos por los sentidos pero es una experiencia que sale de adentro es una experiencia en que de  
[00:30:36](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1835.76s&t=1836s) -> 00:30:54 : repente la criatura siente piensa que algo le falta No sabe qué es pero se siente que algo le falta y en ese momento empieza una búsqueda y en esa búsqueda es donde Dios empieza a actuar  
[00:30:52](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1852.32s&t=1852s) -> 00:31:10 : no lo lleva directamente a a la Biblia no lo lleva directamente teología no no no no lo va llevando a que descubra un mundo que no es nada más material sino que hay algo que  
[00:31:07](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1866.96s&t=1867s) -> 00:31:26 : trasciende la materia y puedes empezar a buscar incluso por vías equivocadas claro por vías equivocadas a buscar no sé esa parte espiritual y ahí si el alma es de buena voluntad Dios se va a  
[00:31:23](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1883.039s&t=1883s) -> 00:31:39 : encargar de irlo guiando guiando guiando hasta que llegue a él pero el movimiento de conversión siempre es interior y de dónde sale de mí Por supuesto que no si soy  
[00:31:36](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1896.24s&t=1896s) -> 00:31:53 : malo no Eso sale de Dios eso sale de Dios eso es exactamente lo que logró la pasión de Jesús lo que logró la vida de María lo que logran las oraciones de todo el mundo de la iglesia las  
[00:31:51](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1910.76s&t=1911s) -> 00:32:08 : oraciones incluso de nuestra madre con San Agustín es un movimiento interior sale aflora Y dice algo me hace falta listo esa persona ya está del otro lado  
[00:32:05](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1925.36s&t=1925s) -> 00:32:22 : entonces esa es una resurrección Esa es la primera resurrección de la que habla San Juan Ay qué interesante Sí nos tenemos que andar más en eso algún día sí tenemos que  
[00:32:18](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1938.36s&t=1938s) -> 00:32:31 : andar más en eso eh doctor entonces por qué se necesitan las almas víctimas todos deberíamos ser víctimas todos todos O sea no es un llamado para unos cuantos como decíamos no qué bueno que  
[00:32:30](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1950.08s&t=1950s) -> 00:32:43 : es el de la casa de enfrente y no de mi casa Perdón pero es que el que no sea alma víctima aquí va a ser alma víctima allá D en el purgatorio claro necesitamos quitarnos todo lo  
[00:32:41](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1960.88s&t=1961s) -> 00:32:59 : nuestro eso es algo que no entendemos todavía decimos soy bueno Y dice uno pero de qué se de qué me hablas Es que yo soy bueno no Mato No robo no hago No no le hago mal a nadie perdón pero eso  
[00:32:54](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1974.0s&t=1974s) -> 00:33:13 : no basta Eso no basta sí necesitamos restituirle a Dios todo el amor que no le hemos dado en cada acto Ay no es muchísimo entonces Quiénes exenta en el purgatorio  
[00:33:09](https://www.youtube.com/watch?v=IyGzo0LUREo&t=1988.679s&t=1989s) -> 00:33:29 : mínimos mínimos por lo tanto quitarme lo nuestro al cielo no entra nada humano nada es Divino No importa lo que hayas hecho en esta vida si lo hiciste con tu voluntad es suo Y eso no  
[00:33:26](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2006.039s&t=2006s) -> 00:33:43 : entra está tremendo está tremendo tremendo Entonces el victimado lo podemos sufrir aquí o lo podemos pasar allá y hay personas que dicen Bueno yo aquí me la paso más o menos bien al  
[00:33:41](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2021.159s&t=2021s) -> 00:33:55 : final pues me arrepiento me pongo en orden con Dios y me voy sí lo que estás acumulando es sufrimiento para allá no y en la teoría los estudiosos del purgatorio dicen que un sufrimiento del  
[00:33:53](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2032.919s&t=2033s) -> 00:34:10 : purgatorio es como si sumamos todos las penas y sufrimientos y dolores y trabajos de la Tierra imí Sí pero no lo pongamos así tan como quererlo en eh en cantidad o o en calidad no se trata de  
[00:34:07](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2047.2s&t=2047s) -> 00:34:27 : de cualificar el sufrimiento se trata de ver lo que estoy haciendo y lo que estoy haciendo en esta vida es algo que me estoy acumulando muerte por favor esto entenderlo es muerte que tengo que ir a  
[00:34:23](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2063.24s&t=2063s) -> 00:34:41 : dejarla ya del otro lado pero que me la van a quitar ya no con actos de mi voluntad ya no es voluntario ojo con eso aquí es muy sencillo quitarlo claro  
[00:34:38](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2077.56s&t=2078s) -> 00:34:54 : sencillo en relación con aquello en relación con aquello pero es dificilísimo aquí s cómo será ya Y por qué Por qué tenerle miedo sería la pregunta en positivo o sea no debemos de  
[00:34:52](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2091.879s&t=2092s) -> 00:35:10 : tenerle miedo por supuesto que no porque cada alma víctima de alguna manera la semejanza con Jesús y eso equivale a una a una irse fundiendo o irse igualando a Jesús que  
[00:35:07](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2107.48s&t=2107s) -> 00:35:26 : eso es lo que vamos a hacer después en el purgatorio entre más Jesús llevemos con nosotros menos problema allá seremos Luz para todos y el alma que vive en la divina voluntad que vive y que vive  
[00:35:23](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2122.96s&t=2123s) -> 00:35:38 : plenamente que verdaderamente vive el purgatorio no tiene nada que hacer con ella No pues no O sea por qué porque ya es Jesús viviendo en esa alma ya Jesús no va a ir al purgatorio eh para vivir  
[00:35:36](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2136.4s&t=2136s) -> 00:35:53 : en en la divina voluntad Como alma víctima tengo que haber purificado todo lo que no hice conforme a la voluntad de Dios sí pero ese es otro punto que es necesario  
[00:35:50](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2149.52s&t=2150s) -> 00:36:09 : entender necesito rehacer mis actos Sí yo puedo rehacer los actos ojo con esto puedo rehacer hac mis actos y aplicármelo a mí por supuesto porque estoy reparando por todos lo lo malo que  
[00:36:06](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2165.599s&t=2166s) -> 00:36:24 : he hecho y estoy requiriendo lo que debería de haber hecho ahora yo puedo reparar por ti claro yo puedo pagarle a Dios por en amor por lo que tú no le diste por qué porque tengo una voluntad  
[00:36:22](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2181.64s&t=2182s) -> 00:36:37 : divina y un Amor divino que es infinito y que abarca todo que alcar No sí pero aquí estamos hablando de vida divina y de Amor divino Okay y el Amor  
[00:36:34](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2194.319s&t=2194s) -> 00:36:52 : divino abarca todo a toda la humanidad y todo lo que la humanidad debería de haber hecho entonces estoy hablando de ti yo puedo rehacer todos tus actos pero no te los puedo  
[00:36:47](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2206.88s&t=2207s) -> 00:37:10 : dar y entonces quedan quedan almacenados ahí junto con lo que Jesús hizo por ti para hacerte más fuerza para que te conviertas pero no te lo puedo aplicar yo no puedo aplicarle a alguien algo  
[00:37:05](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2225.0s&t=2225s) -> 00:37:24 : sino este si no si no lo quiere aquella persona si no lo qui Entonces se queda como una reserva se queda como un empujarlo una fuerza hasta que lo Tum una fuerza que lo va a estar  
[00:37:20](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2240.48s&t=2240s) -> 00:37:38 : moviendo junto con Jesús porque esto sin Jesús no no se puede junto con Jesús para para hacerles fuerza a todos los demás Entonces por qué debo ser víctima por eso porque rehago mi vida porque le  
[00:37:35](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2254.64s&t=2255s) -> 00:37:53 : pago a Dios por todo lo que yo debería de haberle dado y porque de alguna manera me asocio a Jesús para ser más fuerza a todas las almas Sí por qué tenerle miedo pero por favor cuál sería  
[00:37:50](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2270.48s&t=2270s) -> 00:38:07 : el miedo porque dice Jesús que en el momento que el alma Viva en la divina voluntad aparte del sufrimiento de estarse dando muerte a su propio gusto a sus propios actos pero también comparte  
[00:38:05](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2285.04s&t=2285s) -> 00:38:19 : los gozos y la felicidad y la bienaventuranza divina es como darle sentido No si yo le doy el sentido de que que Jesús está viviendo en mí y que estoy restituyendo no solo el pecado  
[00:38:17](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2296.8s&t=2297s) -> 00:38:30 : personal sino el de la humanidad y estoy siendo luz para los demás pues yo creo que eso es muy satisfactorio no es lo mismo yo ofrecer un sacrificio como le hacen los algunos este acetas no hacen  
[00:38:28](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2307.96s&t=2308s) -> 00:38:41 : un ayuno no para ser más perfectos parao ofrecerlo verdad para hacer la voluntad de Dios o por una persona que no se quiera convertir o o para pedirle a Dios por mi familia en fin etcétera etcétera  
[00:38:39](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2318.52s&t=2319s) -> 00:38:57 : no Sí nada más que aquí hay otro hay otra diferencia enorme Por ejemplo tú estás hablando de un sacrificio sí perfecto Ahora yo diría Qué diferencia hay entre el ayuno y el comer si las dos  
[00:38:55](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2334.52s&t=2335s) -> 00:39:10 : lo haces en la divina voluntad ninguno un porque es la divina voluntad porque en los dos te estás negando al acto humano que ese es el verdadero sacrificio por lo tanto aquí el  
[00:39:06](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2345.8s&t=2346s) -> 00:39:25 : sacrificio ya no es ya no es externo y se cumple aquello que se decía en el Antiguo Testamento tus tus ayunos tus sacrificios me son cómo  
[00:39:20](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2359.8s&t=2360s) -> 00:39:37 : decía me son como injuria como Ah no al revés al revés O sea me son injuria porque el ayuno que yo quiero es que veas por la viuda Porque veas por tu prójimo misericordia quiero y no  
[00:39:34](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2374.119s&t=2374s) -> 00:39:53 : sacrificas no Entonces ahora en la divina voluntad es la vida completa de Jesús repitiéndose en la criatura y mortificando pagando por todos y eso no importa donde lo estés  
[00:39:50](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2390.359s&t=2390s) -> 00:40:08 : haciendo No importa pero teniendo en cuenta que teniendo la voluntad divina en ti no puedes querer algo contrario a lo que Dios quiere sí porque se puede tergiversar el sentido decir entonces yo  
[00:40:07](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2406.64s&t=2407s) -> 00:40:20 : voy a vivir en la divina voluntad y voy a vivir como un no sé como un rey sin mortificarme en nada no porque ahí la divina voluntad no podría estar haciendo eso Si nosotros vemos a Jesús como rey  
[00:40:18](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2418.44s&t=2418s) -> 00:40:33 : que está absolutamente mortificado en todo en todo pues lógicamente y queremos repetir la vida de Jesús en nosotros pues tiene que ser así así es Jesús come para vivir no vive para comer claro y  
[00:40:30](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2429.92s&t=2430s) -> 00:40:44 : así por el estilo y y así sucesivamente Así es Ojalá que haya quedado más o menos Claro esto hay mucho hay muchos temas que hablar aquí de de sobre ser víctima y sobre todo hablaremos de cómo  
[00:40:42](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2441.96s&t=2442s) -> 00:41:00 : ofrecerse de como víctima porque hay una oración verdad que que Luisa bueno no no se trata de de actos así como formales Aquí no se trata de consagraciones no se trata de de ofrecimientos  
[00:40:58](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2457.52s&t=2458s) -> 00:41:14 : se trata de un convencimiento de querer vivir en la divina voluntad y de no volver a darle vida a mi querer nada más olvídense de de de que ofrecimientos y que voy a ofrecerme voy a rezar esto no  
[00:41:12](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2472.359s&t=2472s) -> 00:41:26 : no Aquí no se trata de eso muy bien se trata de decisión de vida Yo pensé que tenía que tenía una formalidad en el sentido de que no es lo mismo que yo vaya asumiéndolo a que yo después de  
[00:41:23](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2483.359s&t=2483s) -> 00:41:39 : tener una meditación una oración una preparación pueda decir pues me quio ofrecer comoa Perdón Cuántas almas se consagran a la virgen hay muchas miles millones de almas Cuántas almas viven  
[00:41:36](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2496.0s&t=2496s) -> 00:41:52 : esa consagración pocas ninguna pocas ninguna Yo diría que pocas ninguna porque consagrarse es dedicarse al servicio de por eso pero si hay unas dedicadas dedicadas al servicio en todo  
[00:41:50](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2509.96s&t=2510s) -> 00:42:04 : en todo yo creo que sí doctor aunque sea una pero s la hay Bueno una vamos a concederle a ce una que se Bueno digo Hay pocas no lo que queremos ir Es que hay pocas y creo que con eso terminamos  
[00:42:03](https://www.youtube.com/watch?v=IyGzo0LUREo&t=2522.88s&t=2523s) -> 00:42:11 : porque ya Se nos acabó el Ya se nos terminó amigos Gracias gracias c por Gracias doctor por todo gracias hasta la próxima  