---
title: "¿Quién dices tú que es Jesús?"
thumb: "https://i.ytimg.com/vi/LY9tFIGBDes/maxresdefault.jpg"
tags: [Mundo Católico]
---

 # ¿Quién dices tú que es Jesús? 

 <iframe width="560" height="315" src="https://www.youtube.com/embed/LY9tFIGBDes" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> 

 ## Contenido 


[00:00:04](https://www.youtube.com/watch?v=LY9tFIGBDes&t=4.35s&t=4s) -> 00:00:23 : [Música] el reino de la divina voluntad ya está en medio de las criaturas escucha la espiritualidad dictada a Luisa picarreta por el especialista el doctor Salvador  
[00:00:20](https://www.youtube.com/watch?v=LY9tFIGBDes&t=19.72s&t=20s) -> 00:00:50 : tomasini todos los miércoles de 11 a 12 de la tarde aquí por mundo católico construyendo la civilización del amor [Música] amigos muy buenos días c Buenos días  
[00:00:49](https://www.youtube.com/watch?v=LY9tFIGBDes&t=48.64s&t=49s) -> 00:01:04 : Buenos días doctor Cómo está usted muy bien gracias hay algo que nos está sonando doctor como siempre hay algo que que está sonando que está sonando mi micrófono muy bien muy bien doctor está  
[00:01:01](https://www.youtube.com/watch?v=LY9tFIGBDes&t=60.6s&t=61s) -> 00:01:17 : bien gracias bien cí Y pues aquí para seguir con el programa con los temas que tú que tú has escogido no y que la verdad doctor es que hay mucho de qué hablar y el tema de hoy es muy  
[00:01:14](https://www.youtube.com/watch?v=LY9tFIGBDes&t=73.759s&t=74s) -> 00:01:29 : interesante porque vamos a hablar un poco Sobre qué es lo que tú dices o esta servidora dice o usted que es Jesús di así es No y todo esto lo vamos a ver a la luz de la divina voluntad así es pero  
[00:01:27](https://www.youtube.com/watch?v=LY9tFIGBDes&t=87.36s&t=87s) -> 00:01:41 : antes doctor yo quisiera porque tengo aquí a sus fans un poco enojados porque dice que dicen que lo interrumpo y que se enojan mucho porque lo interrumpo y entonces pues yo quise preguntarle al  
[00:01:38](https://www.youtube.com/watch?v=LY9tFIGBDes&t=98.28s&t=98s) -> 00:01:57 : doctor si a él le molesta que que se le interrumpa Y si usted nos puede decir Bueno okay Yo siempre he pensado que que de hablar dar una especie de plática o  
[00:01:54](https://www.youtube.com/watch?v=LY9tFIGBDes&t=113.56s&t=114s) -> 00:02:12 : algun conferencia o algo así es lo más aburrido que existe en este mundo y es lo más improductivo porque en una plática o sea cuando se está exponiendo un tema El que  
[00:02:09](https://www.youtube.com/watch?v=LY9tFIGBDes&t=128.599s&t=129s) -> 00:02:30 : sea pero sobre todo de esta magnitud que es de religión y con aspectos nuevos genera muchas dudas y cuando surge una duda y no se resuelve en el momento Generalmente Eso hace que se cierre la  
[00:02:26](https://www.youtube.com/watch?v=LY9tFIGBDes&t=146.4s&t=146s) -> 00:02:45 : la persona y ya no reciba el mensaje por puede pensar que está equivocado que es herético que están diciendo totalmente barbaridades cosa contraria si se permite que en ese momento se haga la  
[00:02:41](https://www.youtube.com/watch?v=LY9tFIGBDes&t=161.2s&t=161s) -> 00:03:03 : pregunta se haga el comentario y yo siento que tú tú sé si tienes la la ventaja de tener una una mentalidad O sea que abarca a las personas de afuera así es y nos da nos pone el comentario  
[00:02:59](https://www.youtube.com/watch?v=LY9tFIGBDes&t=179.0s&t=179s) -> 00:03:15 : la duda o incluso el el estar en contra de lo que se está diciendo pero tratando de tomar la la idea de toda la de toda la gente que está fuera y que no conocemos La divina voluntad que somos  
[00:03:14](https://www.youtube.com/watch?v=LY9tFIGBDes&t=193.599s&t=194s) -> 00:03:28 : ignorantes y no hay ningún problema de ser ignorante el problema no es es no reconocerlo ahí bueno entonces yo pienso que esto enriquece el programa o sea realmente  
[00:03:24](https://www.youtube.com/watch?v=LY9tFIGBDes&t=204.159s&t=204s) -> 00:03:44 : creo que lo enriquece y quizás si se corta un poco el hilo pero casi siempre se retoma claro o sea no no se queda no no lo cortamos para no seguirlo Así que yo pienso que no no me  
[00:03:41](https://www.youtube.com/watch?v=LY9tFIGBDes&t=221.12s&t=221s) -> 00:03:58 : molesta Al contrario te lo te lo agradezco nada más que sean cosas muy concretas sobre la divina voluntad y sobre todo sobre el tema que se está tratando Claro claro y también hacerle  
[00:03:56](https://www.youtube.com/watch?v=LY9tFIGBDes&t=236.0s&t=236s) -> 00:04:08 : entender a la gente que nos escucha y que nos hace ese favor que cuando nosotros tratamos estos temas no es para interrumpir al doctor o para lucino nosotros sino precisamente porque  
[00:04:07](https://www.youtube.com/watch?v=LY9tFIGBDes&t=246.92s&t=247s) -> 00:04:19 : consideramos que quien nos está escuchando tendría estas dudas eso es una parte muy importante y la otra que no se trata de una conferencia en donde el doctor esté solito hablando en ese  
[00:04:18](https://www.youtube.com/watch?v=LY9tFIGBDes&t=257.519s&t=258s) -> 00:04:29 : sentido pues no habría para qué interrumpirle Pero esto es un diálogo es un diálogo en confianza verdad aunque le hagamos el anuncio o algún programa que se va sin  
[00:04:27](https://www.youtube.com/watch?v=LY9tFIGBDes&t=266.72s&t=267s) -> 00:04:40 : confianza pero lo importante es que es un diálogo y en ese diálogo pues te puedes situar tú o sea quien sea no entonces pues eso simplemente para decirle a nuestro público verdad la  
[00:04:38](https://www.youtube.com/watch?v=LY9tFIGBDes&t=278.24s&t=278s) -> 00:04:55 : tecnología todavía no alcanza como para hacer un diálogo con todo el mundo ojalá se pudiera verdad tenemos ya la ventaja de que se como son programas en vivo se puede incluso mandar dudas a través de  
[00:04:51](https://www.youtube.com/watch?v=LY9tFIGBDes&t=291.199s&t=291s) -> 00:05:13 : la del mismo canal de YouTube y podríamos irlas más o menos pues viendo si es posible no pero a veces es mucho el volumen Y eso sí interrumpiría totalmente el el tema así es doctor pero  
[00:05:10](https://www.youtube.com/watch?v=LY9tFIGBDes&t=310.08s&t=310s) -> 00:05:28 : de todas maneras o sea crean que es con la mejor intención de hacer un diálogo entre ustedes y y nosotros y todo a través de ci y mío y darle las gracias doctor porque se necesita tener mucha  
[00:05:25](https://www.youtube.com/watch?v=LY9tFIGBDes&t=325.4s&t=325s) -> 00:05:38 : paciencia porque s lo interrumpo y y le pido una disculpa si eso pudiera molestar al público y pudiera molestarlo a usted pero no lo hago con el ánimo de interrumpirlo sino con el ánimo de que  
[00:05:36](https://www.youtube.com/watch?v=LY9tFIGBDes&t=335.6s&t=336s) -> 00:05:51 : todos disfrutemos un poco más al doctor y le preguntemos todas nuestras dudas a mí cuando se me sienta él aquí digo aprovecha el el el esfuerzo del doctor por venir porque a veces tiene que salir  
[00:05:48](https://www.youtube.com/watch?v=LY9tFIGBDes&t=347.96s&t=348s) -> 00:06:03 : fuera tiene muchos compromisos aprovecha el doctor Aprovecha todo lo que lo que él sabe su conocimiento y enriquece a todos los que eh Te escuchan y nos hacen favor de escuchar Así que vamos a  
[00:06:00](https://www.youtube.com/watch?v=LY9tFIGBDes&t=360.479s&t=360s) -> 00:06:18 : iniciar nuestro tema doctor Quién es Jesús para usted Bueno este este este título del programa nace de una una parte del Evangelio cuando Jesús les pregunta a sus discípulos Quién dice la  
[00:06:15](https://www.youtube.com/watch?v=LY9tFIGBDes&t=374.72s&t=375s) -> 00:06:33 : gente que soy yo entonces les responden y les dicen Bueno pues unos dicen que eres este un profeta que eres Elías que eres Juan El Bautista en fin pero después Jesús es más directo y le dice  
[00:06:30](https://www.youtube.com/watch?v=LY9tFIGBDes&t=389.8s&t=390s) -> 00:06:49 : de acuerdo pero y ustedes quién dicen que soy yo y í hay la famosa respuesta de Pedro la el elogio de Jesús para Pedro porque es su padre quien le acaba de revelar aquello y a los pocos minutos  
[00:06:45](https://www.youtube.com/watch?v=LY9tFIGBDes&t=405.16s&t=405s) -> 00:07:06 : le dice aléjate de mí Satanás Sí en fin es curioso este este tema pero ahora es quién decimos nosotros todos nosotros Quién es Jesús Cuál es la idea general este c la idea  
[00:07:04](https://www.youtube.com/watch?v=LY9tFIGBDes&t=423.599s&t=424s) -> 00:07:21 : general de Quién es Jesús Pues la verdad es que eh tengo unos meses y se lo confieso preguntándome si realmente conozco a Jesús es decir eh nosotros tenemos un Jesús evangélico sí que es el  
[00:07:19](https://www.youtube.com/watch?v=LY9tFIGBDes&t=439.4s&t=439s) -> 00:07:33 : que conocemos a través del de las escrituras y del Evangelio concretamente evel lo conocemos por lo que nos ha dicho él mismo de su propia boca y que está escrito en el evangelio y lo que la  
[00:07:30](https://www.youtube.com/watch?v=LY9tFIGBDes&t=449.68s&t=450s) -> 00:07:47 : tradición la iglesia nos ha dicho sobre y transmitido sobre la persona de Cristo pero cuando uno se adentra un poquito más en en buscarle a él en lo personal o sea buscarlo como persona como como como  
[00:07:45](https://www.youtube.com/watch?v=LY9tFIGBDes&t=464.52s&t=465s) -> 00:08:02 : Dios y hombre verdadero se da cuenta que Jesús tiene un corazón de hombre Así es sí un corazón de carne que siente que quiere que tiene anhelos sueños y que además tiene una perspectiva  
[00:08:00](https://www.youtube.com/watch?v=LY9tFIGBDes&t=479.759s&t=480s) -> 00:08:14 : sobre todo cuanto existe o sea no no es cualquier persona que queramos conocer sino es el hombre Dios Entonces llevo muchos meses diciendo Jesús quién eres Jesús dime quién eres Entonces el doctor  
[00:08:11](https://www.youtube.com/watch?v=LY9tFIGBDes&t=490.68s&t=491s) -> 00:08:25 : me dice ci te gustaría hacer un programa de Quién es Jesús pero prepárate digo Sí pues es que llevo muchos meses preguntándome Jesús dime quién eres dime quién eres y y y esta búsqueda no es una  
[00:08:24](https://www.youtube.com/watch?v=LY9tFIGBDes&t=503.96s&t=504s) -> 00:08:40 : búsqueda eh cómo explicar doctrinal no es una búsqueda de de de llenar un hueco no es una búsqueda amorosa una búsqueda de saber porque Sabiendo quién eres  
[00:08:37](https://www.youtube.com/watch?v=LY9tFIGBDes&t=516.64s&t=517s) -> 00:08:55 : tú Puedo amarte más puedo Puedo conocerte más puedo estar más unida a ti Pero si no te conozco y no te y no sé quién eres verdad te tengo ahí lejano en un evangelio que de vez en cuando leo en  
[00:08:52](https://www.youtube.com/watch?v=LY9tFIGBDes&t=531.68s&t=532s) -> 00:09:09 : la semana santa Eh pues no podré tener una una un intercambio de mi voluntad un intercambio de Vidas un un ofrecimiento Como alma víctima pues mucho menos así es entonces Esa es mi pregunta doctor  
[00:09:05](https://www.youtube.com/watch?v=LY9tFIGBDes&t=545.48s&t=545s) -> 00:09:24 : Quién es Jesús para mí y Quién es Jesús en realidad también porque Jesús se manifiesta de manera personal a cada uno de nosotros sí así es o sea dentro de lo que acabas de decir hay algo que que es  
[00:09:21](https://www.youtube.com/watch?v=LY9tFIGBDes&t=560.519s&t=561s) -> 00:09:38 : muy importante recalcar Por qué dices Bueno hay que conocer a Jesús para saber exactamente quién es y yo te diría hay que conocer a Jesús para saber quién es pero sobre todo para saber quién soy Ah  
[00:09:34](https://www.youtube.com/watch?v=LY9tFIGBDes&t=574.399s&t=574s) -> 00:09:55 : interesante quién soy Quién eres tú sí o sea esto que parece así como medio raro si yo no conozco a Jesús si no tengo una idea Clara de Quién es Jesús Nunca podré llegar a conocer quién soy yo claro Sí  
[00:09:53](https://www.youtube.com/watch?v=LY9tFIGBDes&t=592.68s&t=593s) -> 00:10:10 : claro Entonces porque el único que sabe Perdón la interrupción el único que sabe realmente quién soy es él porque es Dios así es o sea nadie nadie más sabe quién soy yo sino él sí pero  
[00:10:06](https://www.youtube.com/watch?v=LY9tFIGBDes&t=605.88s&t=606s) -> 00:10:22 : más que más que eso Acuérdate de la famosa frase que hemos hablado Ya varias veces de que no la hemos entendido nunca hemos profundizado fuimos creados a imagen y  
[00:10:19](https://www.youtube.com/watch?v=LY9tFIGBDes&t=618.519s&t=619s) -> 00:10:39 : semejanza de Dios en su hijo Jesucristo por lo tanto si soy imagen y semejanza de Dios en su hijo forzosamente debo ser Exactamente igual que su hijo si no soy igual que él nunca  
[00:10:35](https://www.youtube.com/watch?v=LY9tFIGBDes&t=635.0s&t=635s) -> 00:10:54 : estaré en el punto en el plano de lo que Dios quiso de mí Por lo tanto para conocerme a mí Necesito conocer a Jesús plenamente y esto es evangélico primero ya lo hemos repetido  
[00:10:51](https://www.youtube.com/watch?v=LY9tFIGBDes&t=651.279s&t=651s) -> 00:11:11 : Perdón que lo que lo volvamos a traer pero las frases de Jesús Tengo mucho que decirles ahorita no con ello el espíritu santo los va a conducir hasta la verdad plena la verdad es Jesús s Entonces qué  
[00:11:08](https://www.youtube.com/watch?v=LY9tFIGBDes&t=668.399s&t=668s) -> 00:11:24 : quiere decir que está diciendo Jesús no me conocen No me conocen el espíritu santo algún día va a ir revelando poco a poco quién soy yo para que me conozcan en  
[00:11:21](https://www.youtube.com/watch?v=LY9tFIGBDes&t=681.04s&t=681s) -> 00:11:36 : totalidad segunda parte del Evangelio que es importante tener en mente el prólogo de de San Juan empieza O sea que el verbo estaba con Dios que la palabra estaba con Dios que  
[00:11:34](https://www.youtube.com/watch?v=LY9tFIGBDes&t=693.72s&t=694s) -> 00:11:55 : él era Dios en fin todo pero al final dice y el verbo se hizo Carne no tomó carne se hizo carne son dos dos hechos que son totalmente diferentes tomar carne es tomar una  
[00:11:51](https://www.youtube.com/watch?v=LY9tFIGBDes&t=711.04s&t=711s) -> 00:12:12 : humanidad común como la nuestra y en ella introducirse el verbo Entonces el verbo estaría eh iba yo a decir usurpando pero no es así O sea estaría tomando una eh una eh  
[00:12:09](https://www.youtube.com/watch?v=LY9tFIGBDes&t=729.399s&t=729s) -> 00:12:29 : humanidad a semejanza del hombre ojo con esto a semejanza del hombre o sea para actuar como hombre para ser como hombre para tener las cualidades como hombre y ahí injertar su  
[00:12:25](https://www.youtube.com/watch?v=LY9tFIGBDes&t=745.04s&t=745s) -> 00:12:49 : divinidad eso sería tomar carne pero hacer carne es la divinidad Ella misma se forma su propia humanidad para trabajar Unidos exactamente la divinidad y la humanidad en una Unión totalmente  
[00:12:45](https://www.youtube.com/watch?v=LY9tFIGBDes&t=765.32s&t=765s) -> 00:13:02 : inseparable donde la divinidad pueda actuar con todo lo que ella es pero en el adtra de Dios o sea en la creación La pregunta sería aquí doctor en el caso de de Jesús ya no es posible separarlo de  
[00:13:01](https://www.youtube.com/watch?v=LY9tFIGBDes&t=780.92s&t=781s) -> 00:13:16 : su humanidad absolutamente hasta el fin digo hasta eterno es eterno es desde Toda la eternidad hasta Toda la eternidad o sea en este punto en  
[00:13:14](https://www.youtube.com/watch?v=LY9tFIGBDes&t=793.88s&t=794s) -> 00:13:33 : este punto esto que voy a decir puede resultar medio escandaloso pero el verbo ha sido ha sido hombre desde Toda la eternidad Dios ha sido hombre desde Toda la eternidad en el verbo encarnado Y eso  
[00:13:31](https://www.youtube.com/watch?v=LY9tFIGBDes&t=810.92s&t=811s) -> 00:13:48 : nos nos da una primacía extraordinaria a los seres humanos por supuesto por eso es que San Pablo creo que San Pablo es el que más concreto nos lo dice primero nos habla de que Jesús  
[00:13:46](https://www.youtube.com/watch?v=LY9tFIGBDes&t=825.88s&t=826s) -> 00:14:05 : es el primogénito de toda la creación el primogénito hermoso por lo tanto o sea el primer hombre el primer hombre es Jesús y no dice primogénito de los hombres no dice primogénito de toda de  
[00:14:01](https://www.youtube.com/watch?v=LY9tFIGBDes&t=841.16s&t=841s) -> 00:14:24 : toda la creación o sea el primer ser creado o sea así como con palabras de San Pablo primer ser creado en toda la historia es la humanidad del verbo eterno que en el tiempo se va a llamar  
[00:14:19](https://www.youtube.com/watch?v=LY9tFIGBDes&t=858.959s&t=859s) -> 00:14:41 : Jesús Sí si Dios tiene un solo acto es acto único ese acto en ese acto único está encerrado todo lo que Dios hace todo lo que Dios quiere no hay actos sucesivos en Dios por lo tanto la la el  
[00:14:39](https://www.youtube.com/watch?v=LY9tFIGBDes&t=879.0s&t=879s) -> 00:14:56 : formar su propia humanidad el tomar carne el volverse carne es desde Toda la eternidad por lo tanto Desde cuando el verbo es hombre no tiene principio ni fin es  
[00:14:54](https://www.youtube.com/watch?v=LY9tFIGBDes&t=894.04s&t=894s) -> 00:15:14 : eterno junto con Dios o sea Dios no tiene un principio nunca decir que Jesús no sería el mismo si no tuviese carne Si no tuviese cuerpo bueno es que si hablas de Jesús pues es Jesús es es la  
[00:15:09](https://www.youtube.com/watch?v=LY9tFIGBDes&t=909.279s&t=909s) -> 00:15:27 : naturaleza humana de Dios Entonces no no existiría como persona de la Trinidad Si no tuviera humanidad no existiría como persona de la Trinidad trad Si no tuviera humanidad  
[00:15:24](https://www.youtube.com/watch?v=LY9tFIGBDes&t=924.279s&t=924s) -> 00:15:43 : lo ponemos No el verbo el verbo eterno es segunda persona de la Sí ahora Aquí el problema está en esto que siempre hemos pensado que la Encarnación el tomar carne la segunda persona es una  
[00:15:41](https://www.youtube.com/watch?v=LY9tFIGBDes&t=940.68s&t=941s) -> 00:15:54 : acción secundaria posterior al pecado Ah interesante o sea posterior al pecado porque nos dicen que el verbo se tuvo que  
[00:15:51](https://www.youtube.com/watch?v=LY9tFIGBDes&t=950.92s&t=951s) -> 00:16:09 : anonadar tuvo que tomar carne para venir a redimir al hombre de acuerdo bueno eso eh en cierta forma es verídico que ahora tiene que venir a redimir pero si él es el primogénito toda la creación fue  
[00:16:08](https://www.youtube.com/watch?v=LY9tFIGBDes&t=967.8s&t=968s) -> 00:16:24 : hecha para él por lo tanto la finalidad de la de la creación y la finalidad del tomar carne el verbo eterno es para Dios no es no es para  
[00:16:21](https://www.youtube.com/watch?v=LY9tFIGBDes&t=980.56s&t=981s) -> 00:16:38 : nosotros no es para venir a salvarnos y cuál sería Entonces el objetivo ahí Tendremos que hablar de la de Cuál es la la finalidad de la creación la finalidad de la creación creo que ya la hemos  
[00:16:34](https://www.youtube.com/watch?v=LY9tFIGBDes&t=993.92s&t=994s) -> 00:16:53 : tratado aquí es Dios quiere amar Dios es amor y quiere amar necesita amar porque su naturaleza es amor y el amor en Dios es darse no es un sentimiento no es querer  
[00:16:50](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1009.839s&t=1010s) -> 00:17:08 : a alguien sino es darse totalmente a alguien pero no hay nadie absolutamente nadie fuera de Dios por lo tanto Dios necesita un ser igual a él igual a él en Inmensidad en  
[00:17:05](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1025.199s&t=1025s) -> 00:17:24 : eternidad en poder en todo para que pueda recibir a Dios mismo precioso y luego quiere ser retribuido no es nada más darse y ya sino también el segundo movimiento del  
[00:17:21](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1040.959s&t=1041s) -> 00:17:37 : Amor amor Así es el segundo movimiento del amor es ser retribuido ser correspondido en amor no hay nadie está el padre el hijo que el padre se dio el hijo correspondió y  
[00:17:35](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1054.559s&t=1055s) -> 00:17:50 : de ahí se forma esta cómo diríamos este movimiento completo del amor y el Espíritu Santo es el que lo encierra Sí pero ahora el espíritu santo encierra ese esos  
[00:17:47](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1067.2s&t=1067s) -> 00:18:04 : movimientos y esos movimientos conforman la vida divina ahora esa vida divina siendo amor necesita darse pero no hay nadie a quien darse Entonces el hijo en en ese sentido está  
[00:18:02](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1082.28s&t=1082s) -> 00:18:21 : cumpliendo la función de poder retribuirle al padre correctamente o Al mismo nivel tanto en el adintra que en el adintra le corresponde como verbo eterno como segunda persona pero en é ad  
[00:18:16](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1096.36s&t=1096s) -> 00:18:35 : extra tiene que tomar carne volverse carne ponerse fuera para que ahora el padre bueno la divinidad pueda darse a él y pueda retribuir entonces cuando las palabras de de Dios en el Génesis de  
[00:18:33](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1113.28s&t=1113s) -> 00:18:50 : hagamos al hombra nuestra imagen y semejanza están relacionadas con el verbo claro es el verbo eterno pero ya en carne o sea no nos hizo imagen y semejanza de él en el verbo sino en  
[00:18:47](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1126.84s&t=1127s) -> 00:19:05 : Jesús en su hijo Jesús Sí por eso es que tenemos una naturaleza física una naturaleza hecha a imagen del verbo del verbo encarnado por eso es que incluso lo  
[00:19:01](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1140.96s&t=1141s) -> 00:19:20 : externo tu figura debe ser divina es que sí no no no pero es que sí pero no es que lo sea no En ese sentido no pero tiene que ser divinizada no es divina por el por el solo hecho de ser imagen y  
[00:19:18](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1158.039s&t=1158s) -> 00:19:35 : semejanza por el solo hecho de ser imagen de la humanidad del verbo y eso lo dice el catecismo Está hermoso eso no es eso no es de divina voluntad de Luis eso es el catecismo que aún la parte  
[00:19:32](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1172.24s&t=1172s) -> 00:19:54 : externa tiene que ser divina porque somos creados a imagen del verbo encarnado entonces espérame si no fuera así si el verbo se hubiera encarnado en una humanidad de como la nuestra nunca  
[00:19:51](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1190.799s&t=1191s) -> 00:20:10 : podríamos ser imagen de él porque él sería imagen nuestra Ah claro sería al revés y no es así y no es así Nosotros somos a imagen de él por lo tanto el primer ser creado ya como  
[00:20:06](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1206.32s&t=1206s) -> 00:20:27 : hombre como ser humano es él Aunque no podamos entenderlo cómo en el sentido de de de un principio yo pienso que sí lo podemos entender sí sí O sea si si tomamos en cuenta estos quizá con las  
[00:20:23](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1223.039s&t=1223s) -> 00:20:41 : palabras de San Pablo nos quedan un poco cortas Porque si me dicen que él es el primogénito de toda la creación yo digo un momento Qué quiere decir eso que es el primero Se supone por eso pero pero  
[00:20:37](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1237.08s&t=1237s) -> 00:21:01 : en en una realidad no en un contexto ya humano aquí me suena irreal Claro claro me suena irreal que que Jesús que vino miles de años después sea el primero el primer ser creado Entonces lo tomo no sé  
[00:20:57](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1256.799s&t=1257s) -> 00:21:16 : yo pienso que en forma retórica sí se entiende no O sea en una en una forma como una no sé como una como una poesía Casi casi como una poesía pero no como una  
[00:21:13](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1273.44s&t=1273s) -> 00:21:33 : realidad no como una realidad pero si tomamos en las palabras de San Pablo y las conjunt con lo que el espíritu santo nos va revelando a través de Luisa vamos entendiendo que es la esta armonía que  
[00:21:30](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1289.679s&t=1290s) -> 00:21:47 : existe en la divinidad es una armonía que se que se totaliza que se completa en el verbo encarnado y entonces el verbo encarnado es el que le da plenitud al amor de Dios  
[00:21:43](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1303.44s&t=1303s) -> 00:22:03 : desde Toda la eternidad y recordemos que el verbo encarnado es cabeza cabeza y nosotros somos miembros de un cuerpo de él y que no es solamente metafórico no es metafórico  
[00:21:59](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1319.159s&t=1319s) -> 00:22:17 : Aquí bueno el tema es muy largo pero creo que nada más dicho así Dios cuando cuando Dios decide hacer una obra que va a ser de beneficio universal primero lo tiene que tratar  
[00:22:16](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1336.08s&t=1336s) -> 00:22:35 : con uno cuando ese uno le corresponde entonces lleva a cabo ya su plan y lo pone a disposición de todos ejemplo en La redención la trata  
[00:22:31](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1351.48s&t=1351s) -> 00:22:50 : con María o sea María siendo inmaculada ya hemos hablado de lo que quiere decir inmaculada en en el momento de la prueba de de nuestra madre en ese momento ella conoce todo lo que Dios ha hecho conoce  
[00:22:47](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1367.4s&t=1367s) -> 00:23:05 : todo lo que el hombre hizo conoce todo lo que Dios tiene que hacer para restituir al hombre y Ella le corresponde a Dios a nombre de todos en amor Por toda la humanidad hacia Dios Y  
[00:23:03](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1382.559s&t=1383s) -> 00:23:22 : eso lo puede hacer Gracias a que está viviendo dentro de ese ambiente eterno de la divina voluntad y ahí nos engloba a todos porque ahí estamos todos y le paga a la divinidad en amor por todos le  
[00:23:19](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1399.159s&t=1399s) -> 00:23:35 : paga por todos los pecados que hemos cometido por todas las faltas por todo lo que hemos hecho y cuando en ella obtiene eso Entonces ahora deci que ya el verbo se encarne en ella y  
[00:23:32](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1412.0s&t=1412s) -> 00:23:48 : empieza todo ese proceso que conocemos como la vida de Jesús y el movimiento de redención del hombre el problema es que lo hemos dejado a nivel de redención o sea lo hemos dejado a nivel  
[00:23:46](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1425.72s&t=1426s) -> 00:24:04 : de salvación a nivel de perdón a nivel de restitución de la gracia Pero nunca lo hemos enfocado al nivel de del segundo Adán que la iglesia no nos propone y el  
[00:24:00](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1439.96s&t=1440s) -> 00:24:17 : es el segundo Adán y yo pregunto a ver si es el segundo Adán Qué es lo que tiene que hacer Jesús qué tendría que hacer como segundo Adán como segundo Adán cuál es su  
[00:24:15](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1454.799s&t=1455s) -> 00:24:30 : función su función es restituir al primer Adán Pero restituir qué quiere decir volver las cosas al Estado original volver todo al Estado original no es conseguir el perdón cl no no no no  
[00:24:27](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1467.12s&t=1467s) -> 00:24:40 : es un Perdón es un perd eso es lo de menos Está peor esto es mucho más violento porque significa regresar las cosas al Estado original al Estado original es como si ahorita un ejemplo  
[00:24:38](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1477.799s&t=1478s) -> 00:24:54 : burdo agarro me paro y tiro una lámpara o una cámara y la rompe y la rompo digo Híjole y yo digo Ay perdóname y tú me dices s Sí cómo no doctor Pero pase a pasar a pagar la cuenta o sea hay que  
[00:24:51](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1491.08s&t=1491s) -> 00:25:08 : restituir lo que se lo que se perdió Claro ese es el punto y a eso viene Jesús y por eso es por eso entendemos en las horas de la pasión que él sigue purificando y sigue sigue Sufriendo y el  
[00:25:04](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1504.399s&t=1504s) -> 00:25:21 : padre dice todavía no todavía no por eso o sea sigue es un movimiento continuo continuo continuo interesantísimo eso pero entonces tenemos que Jesús viene a restituir todo al punto de origen  
[00:25:19](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1518.52s&t=1519s) -> 00:25:35 : original por eso es el segundo dan porque Adán tenía que es donde Dios quería formar su reino no no se pudo porque Adán destruye al hombre como lo había como lo había  
[00:25:34](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1533.76s&t=1534s) -> 00:25:50 : creado dioso o sea se queda ya no queda el hombre que Dios Creó ya no es imagen y semejanza de su hijo Sí y tiene que reg entonces todo todos los descendientes de  
[00:25:47](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1547.48s&t=1547s) -> 00:26:06 : Adán que somos todos están marcados estamos fuera del plan de Dios por eso es que todo el Antiguo Testamento no importa quién sea Abraham Moisés Isaías todos los profetas todos  
[00:26:02](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1562.44s&t=1562s) -> 00:26:21 : los buenos todos los santos del Antiguo Testamento no pudieron entrar al cielo porque no tenían no tenían el distintivo la imagen y semejanza del hijo interesantísimo por lo tanto  
[00:26:19](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1578.72s&t=1579s) -> 00:26:36 : tuvieron que esperarse a que el hijo eh restituyera esa imagen Y por eso es que Jesús cuando muere baja al seno de Abraham para sacarlos a todos y decirles Aquí está yo ya ya le ya hice lo que  
[00:26:34](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1593.52s&t=1594s) -> 00:26:50 : ustedes deberían de haber hecho y aquí está lo que el padre les da y ahora Vámonos entonces empezamos a tener una idea diferente de Jesús Jesús no es nada más  
[00:26:47](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1607.44s&t=1607s) -> 00:27:04 : el verbo eterno que se Encarna porque el hombre pecó no el verbo eterno toma carne porque esa era la finalidad de la creación el que Dios tuviera un ser ser igual a él en el  
[00:27:01](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1620.88s&t=1621s) -> 00:27:17 : adtra para poder compartir y tener una relación de amor y al mismo tiempo ser modelo Este es el punto más importante para nosotros Porque con el verbo encarnado  
[00:27:15](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1635.12s&t=1635s) -> 00:27:35 : Dios es satisfizo pero Dios es infinito es totalmente inagotable todo lo que él tiene quería más de esos más de esos seres y la única la única forma de poderlo  
[00:27:32](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1651.88s&t=1652s) -> 00:27:52 : hacer es ahora sí creando serese similares a Aquel que había tomado carne que era el verbo eterno encarnado a imagen de él y darles su semejanza Cuál es la semejanza Jesús  
[00:27:50](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1669.919s&t=1670s) -> 00:28:08 : actuando en ellos para que ellos actuaran con la divina voluntad en ellos y actuaran como Dios Y entonces cones dentro de la persona el hombre podría recibir todo el amor de Dios que es todo  
[00:28:05](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1684.799s&t=1685s) -> 00:28:20 : Dios y podría pagarle a Dios con amor pero Amor divino interesantísimo pero tengo dos preguntas controversiales la primera son dos pero yo creo que van  
[00:28:17](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1696.6s&t=1697s) -> 00:28:33 : ligadas cuando Jesús se se come a sí mismo en la Eucaristía Cuál es el efecto de Jesús recibiéndose a sí mismo es es una parte y la otra eh Y esto porque estamos en  
[00:28:31](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1710.919s&t=1711s) -> 00:28:46 : semana santa eh refiere también a la muerte de Jesucristo porque en el caso de la muerte de Jesucristo hay un momento que deja de respirar MM y al dejar de  
[00:28:43](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1723.08s&t=1723s) -> 00:29:00 : respirar deja de existir humanamente MM y deja de vivir no no de existir deja de vivir Okay de vivir en en en el medio en el medio externo en el  
[00:28:57](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1737.48s&t=1737s) -> 00:29:12 : medio ex a mí me gustaría como que me dijera Quién es Jesús y Qué impacto tiene la naturaleza y o sea refiriéndonos a a nosotros cuando Jesús se auto come sí porque eso es una una  
[00:29:10](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1750.2s&t=1750s) -> 00:29:27 : maravilla o sea Cuál es el beneficio para nosotros y qué pasa en el mundo cuando Jesús deja de respirar Sí y deja de hacerlo hasta que resucita porque la resurrección supone una vida nueva pero  
[00:29:24](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1764.48s&t=1764s) -> 00:29:39 : supone respiración Bueno si lo estás viendo muy a lo a lo material impactos lo primero el principio de vida está lando nuest la  
[00:29:37](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1777.159s&t=1777s) -> 00:29:51 : respiración sí de plata que nos un al creador el día que dejamos de respirar ya no estamos aquí ya no estamos aquí Okay Dice que no ha tantos pento porque si no se mueve  
[00:29:49](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1789.44s&t=1789s) -> 00:30:04 : mucho el micrófono Okay entonces es un poco lo que le quiero preguntar estos dos aspectos que nos haga favor de aclarar sí per pero primero vamos a terminar con con lo  
[00:30:01](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1800.919s&t=1801s) -> 00:30:19 : anterior Entonces tenemos ya a un verbo que que que que se vuelve carne desde Toda la eternidad el verbo eterno desde Toda la eternidad tiene dos naturalezas la naturaleza divina que es totalmente  
[00:30:16](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1816.159s&t=1816s) -> 00:30:37 : su propia naturaleza y una naturaleza humana que es formada por él para él y en esa naturaleza humana están puestos todos los mecanismos para que la divinidad pueda actuar con todo su poder  
[00:30:34](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1833.96s&t=1834s) -> 00:30:55 : con igual que si actuara en la Trinidad ahora puede actuar en aquella humanidad y puesta fuera o sea el el verbo encarnado no deja de ser Dios ni ni tiene límites límites en su acción o en  
[00:30:52](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1852.36s&t=1852s) -> 00:31:13 : su poder o en su sabiduría o en nada a veces el verbo encarnado no le comunica a la a su humanidad lo que lo que sabe él por ejemplo aquello de que cuándo cuándo será aquello de la  
[00:31:08](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1868.279s&t=1868s) -> 00:31:26 : destrucción y todo dice eso ni yo lo sé pero ese yo es mi humanidad pero mi divinidad sí lo sabe Pero no es el momento de decirlo pero no Se los voy a decir no Se los voy a  
[00:31:22](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1881.76s&t=1882s) -> 00:31:39 : decir o sea es esa interacción y algo que es importante no sabemos Cómo interactuaba esa divinidad con esa humanidad porque siempre hemos visto a un Jesús humano actuando como nosotros  
[00:31:37](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1897.159s&t=1897s) -> 00:31:56 : siendo bebé siendo niño siendo adolescente siendo adulto haciendo las labores que hacemos todos entonces como que lo conceptu siempre como un ser humano igual a nosotros pero definitivo  
[00:31:52](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1912.039s&t=1912s) -> 00:32:11 : es también erróneo porque es Dios mismo quien está actuando aquellas palabras de él no soy yo quien hace mis obras es mi padre que mora en mí quien hace sus obras en  
[00:32:07](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1926.799s&t=1927s) -> 00:32:24 : mí Qué obras hace el padre el padre está creando continuamente es un movimiento eterno está sosteniendo toda la conservando toda la creación está creando almas continuamente está  
[00:32:21](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1941.08s&t=1941s) -> 00:32:41 : salvando almas está beatificando a todo el cielo está felicitando a todos los habitantes del gloria está haciendo todo entonces en el momento que Jesús está clavando o haciendo una mesa haciendo  
[00:32:37](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1957.36s&t=1957s) -> 00:32:55 : una silla el padre está ahí haciendo junto con él pero está haciendo las obras del padre a través de los actos de Jesús están haciendo los actos divinos a través de los actos de Jesús está  
[00:32:52](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1972.0s&t=1972s) -> 00:33:11 : creando un alma se está eh juzgando Un alma se está conservando toda la creación y como Dios es eterno un solo acto Dios está creando porque la creación es un acto único que está en  
[00:33:08](https://www.youtube.com/watch?v=LY9tFIGBDes&t=1987.6s&t=1988s) -> 00:33:25 : continuo acto de hacerse Dios está haciendo todo por lo tanto en los actos de Jesús está saliendo todo aquello no es nada más el acto humano sino es el acto divino y eso es lo que nos viene a  
[00:33:22](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2002.44s&t=2002s) -> 00:33:37 : revelar ahora el conocimiento de la divina voluntad Cómo interactuaban esas dos naturalezas naturaleza humana y naturaleza divina toda la vida de Jesús toda la  
[00:33:35](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2015.48s&t=2015s) -> 00:33:52 : vida de Jesús desde el momento que se Encarna el verbo en aquella humanidad empieza a restituir al hombre empieza a trabajar a hacer todo lo que el hombre debería de haber hecho  
[00:33:49](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2029.159s&t=2029s) -> 00:34:06 : hacia Dios y empieza a pagarle a la divinidad por todos nosotros o sea empieza a vivir la vida de todos nosotros para restituirle al padre lo que lo que él quería recibir en cada uno  
[00:34:04](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2044.36s&t=2044s) -> 00:34:21 : de nosotros En cada uno de no lo recibe o no lo está recibiendo Así es entonces la vida que Jesús está llevando a ver si esto se entiende Ojalá yo espero que sí la vida que se está que está llevando  
[00:34:19](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2059.2s&t=2059s) -> 00:34:37 : Jesús no es la suya es la nuestra es la nuestra porque está haciendo todo lo que nosotros de íamos de haber hecho está pagándole al padre por todo  
[00:34:33](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2072.639s&t=2073s) -> 00:34:49 : lo que nosotros no le hemos dado estar eh incluso está sufriendo las penas que nuestros actos pecaminosos merecen Nosotros hemos acostumbrado a  
[00:34:47](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2086.919s&t=2087s) -> 00:35:04 : decir que Jesús toma sobre de él nuestras culpas que se vuelve pecado por nuestros pecados de acuerdo pero y los demás actos Está terrible los demás actos los actos  
[00:35:00](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2100.28s&t=2100s) -> 00:35:20 : que no son pecado pero que han no han sido hechos para amar a Dios para para para corresponderle sonos todo eso lo tiene que tomar Jesús por lo tanto Jesús toma no solo nuestros pecados toma toda  
[00:35:17](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2116.92s&t=2117s) -> 00:35:37 : nuestra vida por lo tanto la vida que está viviendo Jesús es la nuestra de acuerdo ahora al punto este de la de la de la eucaristía Pero antes de  
[00:35:32](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2132.48s&t=2132s) -> 00:35:53 : eso está Jesús ahí en en la última cena y está dándonos la clave de cómo va a ser posible que el hombre se restituya a la imagen y semejanza cuando dice yo en ellos te acuerdas tú en m tú en mí  
[00:35:50](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2150.4s&t=2150s) -> 00:36:10 : para que ellos sean uno en nosotros como tú como tú y yo somos uno la oración de Jesús al padre así es entonces ahí nos deja dicho ya Cómo cómo es que vamos a restituir al punto original con él  
[00:36:07](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2166.76s&t=2167s) -> 00:36:25 : dentro de nosotros lo necesitamos a él dentro pero no un dentro nada más morando sino lo necesitamos actuando Porque si fuimos creados a imagen y semejanza Entonces nosotros  
[00:36:22](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2181.96s&t=2182s) -> 00:36:39 : tenemos que decir no soy yo quien hace mis obras es el padre celestial quien hace sus obras a través de mí esto es así medio Entonces entonces cada uno de nosotros en el momento que  
[00:36:37](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2196.88s&t=2197s) -> 00:36:51 : que que viviéramos en divina voluntad ya no realizamos los actos propios sino los actos de Jesús por tanto son actos divinos y por tanto nosotros adquirimos una estatura distinta Así es somos seres  
[00:36:48](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2208.4s&t=2208s) -> 00:37:09 : divinizados eso es lo que dice exactamente este su santidad Benedicto 16 en esa presentación que ya hemos hablado donde él va poco a poco de poniendo que no somos somos un proyecto  
[00:37:05](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2225.48s&t=2225s) -> 00:37:21 : incompleto Cómo se llegará a ese a ese a ese momento de llegar a ser hombre Cómo se realiza este llegar a ser hombre es un es un cuestionamiento que él se hace pero que deja muy claro que todavía no  
[00:37:21](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2240.68s&t=2241s) -> 00:37:37 : somos hombres estamos en el proceso de en un proceso y él lo va desglosando poco a poco diciendo que debemos adoptar la voluntad de Dios que al principio es una  
[00:37:34](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2253.52s&t=2254s) -> 00:37:52 : voluntad externa que a la cual me someto más o menos De buena gana pero que poco a poco se va acercando acercando acercando hasta que al final dice el hombre cuando Integra la voluntad divina  
[00:37:50](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2269.88s&t=2270s) -> 00:38:12 : como propia cuando adopta la voluntad divina como propia el hombre llega a su plenitud se hace divino se hace divino y el hombre es ahora sí perfecto hombre o sea que él ya ya entr veía todo esto y  
[00:38:09](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2289.04s&t=2289s) -> 00:38:23 : lo fue manifestando y ahí están sus sus este sus documentos donde lo va diciendo Entonces cuando el el momento quizás los momentos de nuestra vida en donde nosotros  
[00:38:21](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2301.28s&t=2301s) -> 00:38:38 : recibimos la Eucaristía son los momentos en donde Jesús está obrando a través de mí y y está está haciendo su divina voluntad en mí no no porque en el momento que  
[00:38:35](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2314.76s&t=2315s) -> 00:38:55 : bueno Jesús está a punto de terminar su vida en la tierra está en ese momento allí en el cenáculo y él dice en su en en los escritos de Luisa dice mi amor Me dijo La redención  
[00:38:51](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2330.96s&t=2331s) -> 00:39:08 : prácticamente está cumplida Pero y mi reino dónde está o sea cuál es su reino el reino de la divina voluntad obrante en la criatura el Fiat voluntad tua sí como en el cielo  
[00:39:06](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2346.2s&t=2346s) -> 00:39:26 : Así en la tierra no está Entonces quédate con ellos Quédate con ellos para que los vayas instruyendo Los vayas llevando poco a poco hasta llegar a ese punto de  
[00:39:22](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2362.04s&t=2362s) -> 00:39:40 : mi reino por eso es que se instituye la Eucaristía como una ayuda para irnos acostumbrando a la presencia de Jesús en nosotros pero la promesa es quedarse en la  
[00:39:36](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2376.16s&t=2376s) -> 00:39:55 :  la es un vehículo Para yo poder acceder a él yo tengo que ir a tomarlo y la promesa es en la mientras la la sustancia de la  persiste Ahí está  
[00:39:52](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2392.2s&t=2392s) -> 00:40:11 : Jesús en el momento en el que la la  se disuelve por efecto la vida real de Jesús se va y eso es catecismo y doctrina de la iglesia eso no es no es nada raro Nada nuevo por lo  
[00:40:08](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2408.319s&t=2408s) -> 00:40:27 : tanto no es un Jesús obrante no es un Jesús que que obre es un Jesús que llega que llega a a estar con nosotros que llega para que podamos entablar una comunicación mientras él  
[00:40:23](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2423.24s&t=2423s) -> 00:40:44 : está en nosotros y no para ir a cantar no esto Esto sí es totalmente una un una una crítica o sea ese momento es para estar entrar en una intimidad con Jesús en una intimidad ya si no tengo nada que  
[00:40:40](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2440.48s&t=2440s) -> 00:40:58 : decirle cuando menos decirle señor habla tu siervo te escucha no habla o te amo y gracias Ya un te amo en silencio verdad Así es Entonces es ese Jesús que entra y cuando se va cuando la vida real de él  
[00:40:55](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2455.16s&t=2455s) -> 00:41:12 : se va me deja Gracias y Gracias infinitas que yo mantengo en mí mientras no peco pero el momento que yo yo lo tomo Ahí está presente ahí está cuando yo me lo trago se desvanece no sigue  
[00:41:10](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2469.96s&t=2470s) -> 00:41:25 : hasta que la se disuelve se deshace dentro y ahí ya se fue aproximadamente 10 15 minutos algo más y y ya se fue y ya se fue la la vida real de  
[00:41:22](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2482.28s&t=2482s) -> 00:41:41 : Jesús O sea la vida real en el momento que eso pasa se va pero me deja la gracia y la gracia son los efectos de la vida divina en mí que yo mantengo el tiempo que yo  
[00:41:38](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2497.56s&t=2498s) -> 00:41:55 : quiera entonces para para que esto para que este Jesús que entra en mí ya entendiendo Quién es Jesús para para pagarle por haberse quedado en la para darle el honor  
[00:41:52](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2512.04s&t=2512s) -> 00:42:13 : el decoro adecuado para para poderlo recibir se tuvo que recibir o sea en primer lugar él tuvo que recibirse a sí mismo para él darse a sí mismo toda la gloria que todo el honor  
[00:42:08](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2528.04s&t=2528s) -> 00:42:27 : que que merecía Y darnos la posibilidad de poderlo recibir si él no se hubiera no se hubiera comulgado a sí mismo nosotros no seríamos capaces de poderlo recibir es un requisito indispensable  
[00:42:25](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2544.72s&t=2545s) -> 00:42:41 : para nuestra propia comunidad claro porque si no si no si él no recibe el pago él nunca se hubiera quedado ahí para que lo recibiéramos indignamente o sea porque él está en el  
[00:42:40](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2559.64s&t=2560s) -> 00:42:55 : momento que él se recibe a sí mismo está haciendo una comunión perfecta y y universal a nombre de de todos los tiempos por lo tanto Entonces ahora yo lo recibo  
[00:42:52](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2572.28s&t=2572s) -> 00:43:15 : indignamente yo lo recibo Incluso en pecado mortal bueno Pero él ya se pagó a sí mismo y entonces ya no ya no no no se niega a entrar porque ya recibió de él lo que yo debería de darle recibe  
[00:43:11](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2591.04s&t=2591s) -> 00:43:32 : también el pecado la ofensa lo que como le quieras llamar sí pero ya tiene el pago por lo tanto ahora acepta entrar en mí y aquí volvemos a lo mismo es Jesús viviendo nuestra vida  
[00:43:28](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2607.92s&t=2608s) -> 00:43:47 : si lo vemos Así es Jesús quien yo en él soy el que estoy comulgando y le estoy dando todo lo que él quiere darse para dejarme ya como un sujeto capaz de poderlo  
[00:43:44](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2624.28s&t=2624s) -> 00:44:03 : recibir igual con toda la humanidad y volvemos al mismo punto es la vida de toda la humanidad La que está viviendo Jesús sí se entiende se entiendo pero es inmenso Así es igual  
[00:44:00](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2639.88s&t=2640s) -> 00:44:18 : que las tentaciones en el desierto todo el mundo piensa que Satanás se le acerca a Jesús a tentarlo a tentar al hombre Jesús perdón pero eso es totalmente ilógico Satanás no se le puede acercar a  
[00:44:15](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2655.319s&t=2655s) -> 00:44:33 : Dios igual que Satanás no se le pudo acercar a la virgen y la virgen que tenía esta vida por participación no por naturaleza Satanás no se le pudo acercar menos se le va a poder acercar a  
[00:44:30](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2670.359s&t=2670s) -> 00:44:50 : la divinidad atentar a la divinidad Entonces cuál sería el la lectura de las tentaciones son nuestras tentaciones nuestra vida nuestra vida nuestra vivida en él Y entonces Satanás  
[00:44:48](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2687.8s&t=2688s) -> 00:45:05 : sí se sí se le puede acercar porque se me está acercando Se te está acercando a ti se me está acercando a mí y nos está tentando en D dond nos duele en donde nos cueste nos duele y Jesús nos muestra  
[00:45:01](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2701.28s&t=2701s) -> 00:45:22 : el camino y la forma de poder vencer las tentaciones o sea en esas tres tentaciones se encierra todo Cuáles son las tentaciones el el dinero el dinero el hambre el hambre sí la fama el poder  
[00:45:18](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2717.599s&t=2718s) -> 00:45:36 : el poder o sea y sobre todo el una una tentación que es Fabulosa adórame Ah sí adórame y el mundo adora adora al digo el hombre adora al mundo y adora al  
[00:45:33](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2733.44s&t=2733s) -> 00:45:51 : enemigo de Dios adora al enemigo sabemos que que el mundo y la carne son enemigos son los enemigos nuestros y nosotros adoramos ahí por lo tanto Satanás ya logró su cometido no en Jesús que era el  
[00:45:49](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2748.72s&t=2749s) -> 00:46:03 : que quería pero sí en sus criaturas hay quien dice sobre las tentaciones y solamente es para completarlo que cuando Satanás se acerca a él para tentarlo es para saber quién es él porque todavía no  
[00:46:00](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2759.96s&t=2760s) -> 00:46:17 : sabe que es el hijo de Dios sa por favor eso es lo mismo que dicen ahora que Jesús tuvo que ir aprendiendo poco a poco Quién era él no pues siempre lo sup que María tuvo que ir poco a poco  
[00:46:13](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2773.079s&t=2773s) -> 00:46:30 : entendiendo Quién era su hijo por favor lo supieron siempre claro y ahora dígame Entonces cuando O sea qué beneficio recibo eh Cuando Jesús Ah ya ya nos dijo algo  
[00:46:28](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2788.48s&t=2788s) -> 00:46:43 : cuando Jesús se recibe as mis la Eucaristía el beneficio que recibo Es que yo sí lo puedo recibir porque Jesús ya tengo el el aval el aval para recibirlo Ya tengo todo lo que Jesús  
[00:46:40](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2800.4s&t=2800s) -> 00:46:58 : hizo por mí ahora me lo da como mío y yo puedo acercarme a la Eucaristía No importa que me acerque Incluso en pecado en pecado qué dolor Así que Jesús aguanta todo porque ya se pagó por todos  
[00:46:56](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2815.88s&t=2816s) -> 00:47:14 : Ahora lo único que hace falta es completar lo que le faltó a la pasión de Jesús y lo que le faltó fui yo claro San Pablo otra vez lo que le faltó y uno dice qué le pudo faltar si  
[00:47:10](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2830.4s&t=2830s) -> 00:47:32 : Jesús es perfecto hizo todo no le falté yo porque yo no he dicho que sí lo hizo todo por mí todo pero le falté yo está fuerte Entonces qué beneficio sacamos ese el iros  
[00:47:27](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2847.4s&t=2847s) -> 00:47:49 : a vivir con Jesús el sacar tener la posibilidad de poderlo recibir hay un cambio genético en m no genético no hay un cambio en mi sangre no porque se hace carne de mi carne y sangre de mi  
[00:47:46](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2865.96s&t=2866s) -> 00:48:05 : sangre por eso adquieres o sea en el momento en el que tú recibes a Jesús lo tienes morando en ti pero no hay una fusión no hay fusión y qué necesitaría para una fusión que que él encontrara en  
[00:48:01](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2881.44s&t=2881s) -> 00:48:21 : ti todo lo adecuado todo lo necesario para que él pueda desarrollar su vida lo primero que necesita es no encontrar un enemigo y el enemigo es tu voluntad Oh DIF lo primero lo segundo necesita  
[00:48:18](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2898.28s&t=2898s) -> 00:48:40 : encontrar todas sus cosas o sea todas sus obras es como si nosotros pudiéramos dijera yo me quiero poner no sé en mi hijo pero voy a entrar en mi hijo pero sin mis obras qué va a  
[00:48:35](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2915.48s&t=2915s) -> 00:48:54 : pasar me voy a volver mi hijo No yo se entiende o no sí es como entonces Jesús tendría que o sea tendría que convertirse en mí no puede no puede porque yo no lo  
[00:48:50](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2929.76s&t=2930s) -> 00:49:07 : dejo no sería totalmente absurdo que la divinidad se quiera convertir en una humanidad sin Dios Ah no obviamente obviamente Entonces se necesita forzosamente que encuentre sus obras en  
[00:49:04](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2944.04s&t=2944s) -> 00:49:21 : nosotros y esas obras son todo lo que Dios ha hecho se necesita encontrar en nosotros y esas obras las contiene la divina voluntad aparte necesita encontrar sus  
[00:49:17](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2957.4s&t=2957s) -> 00:49:36 : atributos Dios no va a venir a obrar con mis atributos con mis virtudes imagínate pobre Dios pobre Dios Jesús yo diciéndole sabes que Jesús vas a venir a obrar con mi obediencia va a decir no no  
[00:49:33](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2973.48s&t=2973s) -> 00:49:50 : con mi pureza madre Sant santísimo Entonces sería su pureza su obediencia su humildad todo sus atributos por lo tanto por eso no se puede quedar Porque primero encuentra su  
[00:49:48](https://www.youtube.com/watch?v=LY9tFIGBDes&t=2987.88s&t=2988s) -> 00:50:05 : enemigo acérrimo que es la voluntad humana no encuentra sus obras y no encuentra sus atributos no puede por eso es que viene lo recibimos pero no hay esa  
[00:50:02](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3002.2s&t=3002s) -> 00:50:18 : fusión sí Hasta que poco a poco vamos nosotros en la medida que yo voy entrando en el en el camino de la santidad y voy a hablar de la santidad humana me voy acercando a él voy voy  
[00:50:15](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3014.64s&t=3015s) -> 00:50:35 : teniendo cierta afinidad de mi voluntad hacia la de él claro y la unión de voluntades va generando una una Unión de pensamiento una Unión de deseo incluso una Unión de obra Pero es en la  
[00:50:32](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3032.04s&t=3032s) -> 00:50:50 : voluntad humana acercándose no apropiándose de las cosas divinas por lo tanto Dios va encontrando almas que cada día están más cerca de él y él puede permanecer más tiempo con ellas a través  
[00:50:47](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3046.68s&t=3047s) -> 00:51:00 : de la gracia es sería una comunión continua Así es o sea en el momento que nosotros hagamos eso es como si estuviéramos dejáramos a Jesús sacramentado tod vida porque yo siempre  
[00:50:58](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3057.599s&t=3058s) -> 00:51:14 : digo no te vayas no te vayas y no se va no se va si realmente llegamos a esa fusión una Conchita Cabrera de Armida que es la Encarnación Mística de él quien te toca a ti toca el  
[00:51:10](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3070.359s&t=3070s) -> 00:51:30 : verbo pero nunca Conchita pudo decir yo hice un acto divino no era no era un Jesús obrante en Conchita el alma que vive en la divina voluntad es un alma que a la divina  
[00:51:27](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3087.48s&t=3087s) -> 00:51:46 : voluntad hacer sus obras a través de las obras de la persona Solamente estoy prestando mi humanidad Por así decirlo para que Jesús obre a través a través de mis actos entonces con esto tenemos ya  
[00:51:43](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3102.799s&t=3103s) -> 00:52:03 : una una idea un poco más clara de Quién es Jesús Jesús verbo eterno con naturaleza humana sí verbo eterno que quiere venir bueno la finalidad de él era venir a establecer su  
[00:51:59](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3119.4s&t=3119s) -> 00:52:19 : reino Quién es el verbo eterno es aquel que viene a pagar a vivir nuestra vida a vivir nuestra vida y a llevarla a donde debe estar Y a dónde debe estar nuestra vida en el  
[00:52:15](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3135.119s&t=3135s) -> 00:52:37 : sepulcro porque nuestra vida es muerte Ah claro el día que comas del fruto de ese árbol irremediablemente morirás y el fruto de ese árbol era el acto humano sin la unión con la voluntad  
[00:52:34](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3154.24s&t=3154s) -> 00:52:55 : divina la separación completa Así es por lo tanto traemos cargando en nosotros muerte Jesús tiene que venir tiene que rehacer lo nuestro pero quitarnos lo que tenemos rehace lo mío y toma lo mío Toma  
[00:52:52](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3172.04s&t=3172s) -> 00:53:10 : lo mío y lo lleva a donde debe estar la pasión de Jesús perdón pero esa es la pasión nuestra claro o sea eso es lo que nosotros deberíamos de haber sufrido para por todo lo que hemos hecho claro y  
[00:53:07](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3186.839s&t=3187s) -> 00:53:25 : luego esta vida que yo tengo tiene que morir y Jesús la lleva se la pone en sí mismo y la lleva al punto de la muerte y tiene que ser muerte real no puede ser como la virgen que fue dormición Sí  
[00:53:24](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3204.119s&t=3204s) -> 00:53:38 : claro porque ella es inmaculada Concepción así es ella es aparte es aparte es un tema aparte Jesús tiene que morir sí tiene que morir porque es nuestra vida la que está llevando al  
[00:53:35](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3214.88s&t=3215s) -> 00:53:50 : sepulcro y tiene que deshacerse en el sepulcro es la única forma de vencer la muerte es con la muerte misma por eso por eso Deja de respirar es que qué interesante por eso Deja de latir Ay qué  
[00:53:47](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3226.839s&t=3227s) -> 00:54:08 : impresion Para que la vida humana que lleva que es la nuestra se deshaga es muerte total y preparar aquel ser para la resurrección porque el que resucita otra vez en Jesús somos  
[00:54:05](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3244.559s&t=3245s) -> 00:54:24 : nosotros la vida que Jesús tiene en el momento de resucitar una vida divina una vida gloriosa una vida o sea diferente Esa es la nuestra que nos la deja a nuestra disposición para primero el día  
[00:54:21](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3260.64s&t=3261s) -> 00:54:39 : que él disponga que la podamos tomar y segundo cuando nosotros nos no dispongamos a tomarla Así que esa es la historia de esta de esta semana santa eh realmente  
[00:54:36](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3276.28s&t=3276s) -> 00:54:58 : la el que Jesús haya dejado de respirar es es algo grandioso Claro porque es ese es el uno de los puntos culminantes en donde la divinidad muestra ese amor inmenso hacia  
[00:54:54](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3293.559s&t=3294s) -> 00:55:17 : hacia la humanidad porque es la misma humanidad del verbo que muere muere por efecto de tomar nuestra vida y resucita requiere su verdadera naturaleza despojándose de nuestra  
[00:55:14](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3314.119s&t=3314s) -> 00:55:35 : naturaleza de nuestra vida que la deja en el sepulcro y viene a una vida ya gloriosa y esa vida gloriosa no es exactamente la de él es la nuestra la vida que tiene actualmente es la nuestra  
[00:55:30](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3329.88s&t=3330s) -> 00:55:48 : Bueno o sea debemos ser exactamente como él y eso lo dice San Juan no Y eso es enseñado por la iglesia siempre que vino enseñarnos el camino de la salvación Sí pero eso es  
[00:55:45](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3345.44s&t=3345s) -> 00:56:01 : salvación o sea Dios Dios en su reino y nosotros súbditos en la visión beatífica de Dios viendo a Dios todo el tiempo no Esa esa idea no después de unos cuantos después de unos  
[00:55:59](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3359.119s&t=3359s) -> 00:56:17 : cuantos siglos decirle sabes queé señor volteate tantito dice para poderte ver de otro lado no eso eso no no no funciona o sea es la vida la vida de Dios en la  
[00:56:14](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3373.839s&t=3374s) -> 00:56:31 : criatura poder interactuar juntos si somos miembros del cuerpo de Jesús debemos estar y hacer lo que Jesús hace y donde esté ahorita en este momento estamos en  
[00:56:28](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3387.96s&t=3388s) -> 00:56:42 : este programa y yo pregunto Y dónde está tu pie derecho Pues bueno no s en este en este programa en este programa y tu pie derecho puede decir estoy haciendo este programa y no le queda otra más que  
[00:56:41](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3401.0s&t=3401s) -> 00:56:53 : estar haciendo este programa ni quiere estar en otra parte porque tendría que estar separado o o podría estar inquieto porque a veces tiene uno las piernas inquietas sí a veces pas eso que tenemos  
[00:56:51](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3410.92s&t=3411s) -> 00:57:11 : los miembros Inquietos pero sí se entiende cuál es esa esa Unión ahora esta este momento este momento de de esta pasión de esta resurrección hay que tenerlo muy en cuenta para poder vivir  
[00:57:06](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3426.4s&t=3426s) -> 00:57:27 : una semana santa continua no una semana santa una vez al año no una semana santa vivida desde Bueno vamos a extenderla Desde el miércoles de ceniza hasta  
[00:57:23](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3442.96s&t=3443s) -> 00:57:44 : resurrección no vamos a vivirla con totalmente en nuestra vida una vida donde yo voluntariamente me una a Jesús para vivir lo que él vivió Y para que lo Viva en mí catecismo de la Iglesia  
[00:57:40](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3459.68s&t=3460s) -> 00:57:57 : Católica o sea él hace que podamos vivir En él todo lo que él vivió y que lo Viva en nosotros De hecho son las palabras de él el que come mi cuerpo y bebe mi sangre yo permanezco en él y él en mí y  
[00:57:53](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3472.559s&t=3473s) -> 00:58:11 : él y él en mí lo cual es inexplicable sola sin sin tener este todo este conocimiento que de la divina volad Así es igual que ese artículo del catecismo donde dice que él hace que nosotros  
[00:58:07](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3487.48s&t=3487s) -> 00:58:25 : podamos vivir todo lo que él vivió en él y que él lo Viva en nosotros parecería lo mismo pero es diferente vivirlo en él es vivirlo hace 2000 años que lo Viva en nosotros es vivirlo el hoy aquí entonces  
[00:58:23](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3503.359s&t=3503s) -> 00:58:37 : no hay tiempo no hay tiempo estamos en el en el ámbito de la divina voluntad que el ámbito de la divina voluntad es la eternidad él abr la bosis y de hecho lo hicimos en un comentario del  
[00:58:34](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3513.839s&t=3514s) -> 00:58:57 : Evangelio el 4 de Febrero de 1956 le dijo Quieres saber el el grado o la entender mi humildad considera mis diferentes nacimientos le dice el primero nací en el seno inaccesible del  
[00:58:55](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3535.28s&t=3535s) -> 00:59:16 : padre segundo nací en el vientre en el seno de una virgen pobre tercero eh nací en la oscuridad de un  
[00:59:11](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3551.319s&t=3551s) -> 00:59:28 : sepulcro y cuarto nací en la las palabras y en la obediencia de las palabras del hombre para hacerme eucaristía preciosísimo porque nosotros estamos  
[00:59:25](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3565.24s&t=3565s) -> 00:59:43 : acostumbrados a ver a Jesús como una totalidad y no nos damos cuenta de de lo que significa él Así es Entonces él en cada acto Está realizando algo magnífico algo que no tiene No tiene  
[00:59:41](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3581.24s&t=3581s) -> 00:59:57 : medida simplemente eterno nacer de una manera inaccesible en en el seno del padre bajar a una virgen pobre hacerse hombre morirse y nacer en un sepulcro  
[00:59:55](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3595.4s&t=3595s) -> 01:00:13 : para resucit y bajar todos los días en la obediencia de las palabras de un hombre o sea Quién es Jesús Quién es Jesús Quién es Jesús y esa es mi pregunta Quién eres tú Bueno  
[01:00:09](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3608.92s&t=3609s) -> 01:00:27 : pues es la respuesta nos la da el catecismo creo que es muy clara el catecismo Pues denos por favor el catecismo nos Define a Jesús como dos naturalezas eh  
[01:00:24](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3623.96s&t=3624s) -> 01:00:42 : distintas perfecto hombre verdadero hombre y verdadero Dios en una sola persona aquí primero tengo que definir Qué quiere decir naturaleza A qué responde la palabra  
[01:00:38](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3637.96s&t=3638s) -> 01:00:59 : naturaleza a lo que es claro qué es eso es naturaleza y la y la palabra persona responde a la pregunta Quién es de acuerdo Bueno entonces son dos naturalezas humana y divina verdadero  
[01:00:55](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3655.2s&t=3655s) -> 01:01:16 : hombre Dios en una sola persona la persona de quién de Cristo no entonces del verbo eterno es mucho más claro porque entonces ahí ya nos está definiendo que el que Jesús es el verbo  
[01:01:13](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3672.68s&t=3673s) -> 01:01:29 : eterno en su naturaleza de hombre pero es el verbo eterno porque el verbo eterno tiene dos naturalezas es Dios pero al mismo tiempo es hombre maravilloso entonces Quién es  
[01:01:27](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3686.559s&t=3687s) -> 01:01:44 : Jesús el verbo eterno para qué está Jesús en este mundo primero para conseguirnos un el el punto principal que es la restitución de nuestra naturaleza  
[01:01:40](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3700.079s&t=3700s) -> 01:01:58 : original segundo tiene que venir primero a conseguir la parte secundaria la parte secundaria era el perdón porque si no hay perdón no podría restituir al punto  
[01:01:55](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3714.839s&t=3715s) -> 01:02:14 : original por lo tanto primero aparece para el mundo aparece la la salvación como punto principal de la venida de Jesús a este mundo bueno esa era necesaria para lograr el verdadero fin y  
[01:02:11](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3730.599s&t=3731s) -> 01:02:30 : el verdadero fin era restituir a nuestro punto de origen claro Así que esta esta semana santa c estás viviendo la restitución de tu naturaleza a la naturaleza creada por  
[01:02:26](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3746.079s&t=3746s) -> 01:02:43 : Dios en Adán a imagen y semejanza de la naturaleza humana del verbo eterno para que yo pueda ser efectivamente ya esa imagen y semejanza y que puedas ser un verdadero ser humano y que puedas tener  
[01:02:39](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3758.96s&t=3759s) -> 01:02:57 : esa relación totalidad en totalidad de amor con Dios con tu creador y y además extraordinaria porque es vida divina Así es ya no es vida humana ya no es vida humana es vida divina y se lo dice Jesús  
[01:02:54](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3773.76s&t=3774s) -> 01:03:12 : Luisa hija por no vivir vida de cielo desde aquí hija Por qué no quieres vivir vida divina hija hija hija Por qué no quieres nada más encuentro lo tuyo dice en unas lecturas n más encuentro lo tuyo  
[01:03:08](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3788.319s&t=3788s) -> 01:03:27 : ya me voy no y hay lecturas preciosas o sea no sé la última la última cosa no sé cómo estamos de tiempo si nos pueden ayudar la última cosa que yo quisiera decir  
[01:03:23](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3802.559s&t=3803s) -> 01:03:43 : el el punto principal es jes nos dice cuando quieras reconocerte reconocerte Ven a reconocerte en mí porque si te reconoces en ti te vas a  
[01:03:39](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3819.2s&t=3819s) -> 01:04:00 : equivocar o sea y una vez reconociéndote a ti en mí vas a reconocer al mismo tiempo a todo todos tus prójimos porque a todos los vas a encontrar en mí entonces necesitamos  
[01:03:56](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3836.0s&t=3836s) -> 01:04:16 : esa idea que mi verdadera identidad está dentro de Jesús Por qué Porque él es el modelo él es el el hombre Dios y nosotros tenemos que tener la naturaleza humana de él  
[01:04:13](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3853.119s&t=3853s) -> 01:04:26 : creada y la naturaleza Divina de él por participación no pu Qué obras realizaremos poreso se realizarán aún mayores Así es extraordinarias doctor yo creo que ya Se nos acabó el tiempo pero  
[01:04:25](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3864.559s&t=3865s) -> 01:04:39 : no no tengo aquí a ver si me pueden echar una mano si ya terminamos el tiempo eh si quieren pasar alguna pregunta ya terminé ya muy bien en Bueno pues sí sí espero que medio  
[01:04:38](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3877.599s&t=3878s) -> 01:04:53 : haya qued no estuvo increíble el programa hermoso dale las gracias doctor desearle lo mejor en esta santa semana santa que la viva con esa intensidad Y la verdad desearle eh las  
[01:04:51](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3891.039s&t=3891s) -> 01:05:04 : mejores pascuas de resurrección gracias gracias a todos Igualmente a todos los que nos ven y nos escuchan una Santa semana santa y nos veremos aquí el próximo miércoles así es eh Y si  
[01:05:01](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3901.24s&t=3901s) -> 01:05:13 : tienen preguntas pónganlas para que el doctor y si quieren temas también para invitar al público que nos de temas que que quieran tratar y también los trataremos aquí en el programa Muchas  
[01:05:12](https://www.youtube.com/watch?v=LY9tFIGBDes&t=3911.92s&t=3912s) -> 01:05:18 : gracias hasta la próxima felices pascuas de resurrección hasta prx hasta luego  